// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t *ui_MainScreen;
lv_obj_t *ui_StatusHeader;
lv_obj_t *ui_RoomTemp;
lv_obj_t *ui_TextRoomTemp;
lv_obj_t *ui_ImageRoomTemp;
lv_obj_t *ui_BuzzerStatus;
lv_obj_t *ui_ImageClock;
lv_obj_t *ui_Minute;
lv_obj_t *ui_Second;
lv_obj_t *ui_TextTime;
lv_obj_t *ui_HeaterSetDock;
lv_obj_t *ui_ImageHeater;
lv_obj_t *ui_TextTarget;
lv_obj_t *ui_TargetTemp;
lv_obj_t *ui_TextTargetTemp;
void ui_event_TempSet( lv_event_t * e);
lv_obj_t *ui_TempSet;
lv_obj_t *ui_HeaterTempDock;
lv_obj_t *ui_BarHeaterTemp;
lv_obj_t *ui_HeaterTemp;
lv_obj_t *ui_TextHeaterTemp;
void ui_event_Setting( lv_event_t * e);
lv_obj_t *ui_Setting;
void ui_event_BuzzerSwitch( lv_event_t * e);
lv_obj_t *ui_BuzzerSwitch;
void ui_event_FanSwitch( lv_event_t * e);
lv_obj_t *ui_FanSwitch;
void ui_event_ScreenSwitch( lv_event_t * e);
lv_obj_t *ui_ScreenSwitch;
void ui_event_StartStop( lv_event_t * e);
lv_obj_t *ui_StartStop;
// CUSTOM VARIABLES


// SCREEN: ui_TemperatureSettingScreen
void ui_TemperatureSettingScreen_screen_init(void);
lv_obj_t *ui_TemperatureSettingScreen;
lv_obj_t *ui_Keyboard;
void ui_event_Confirm( lv_event_t * e);
lv_obj_t *ui_Confirm;
void ui_event_Delete( lv_event_t * e);
lv_obj_t *ui_Delete;
void ui_event_Num0( lv_event_t * e);
lv_obj_t *ui_Num0;
lv_obj_t *ui_NumPanel;
void ui_event_Num1( lv_event_t * e);
lv_obj_t *ui_Num1;
void ui_event_Num2( lv_event_t * e);
lv_obj_t *ui_Num2;
void ui_event_Num3( lv_event_t * e);
lv_obj_t *ui_Num3;
void ui_event_Num4( lv_event_t * e);
lv_obj_t *ui_Num4;
void ui_event_Num5( lv_event_t * e);
lv_obj_t *ui_Num5;
void ui_event_Num6( lv_event_t * e);
lv_obj_t *ui_Num6;
void ui_event_Num7( lv_event_t * e);
lv_obj_t *ui_Num7;
void ui_event_Num8( lv_event_t * e);
lv_obj_t *ui_Num8;
void ui_event_Num9( lv_event_t * e);
lv_obj_t *ui_Num9;
lv_obj_t *ui_TempSettingHeader;
lv_obj_t *ui_TextTempSetting;
lv_obj_t *ui_TempSetting;
lv_obj_t *ui_SetTemp;
lv_obj_t *ui_TextSetTemp;
lv_obj_t *ui_TextCurrentTemp;
lv_obj_t *ui_CurrentTemp;
void ui_event_TempSettingBack( lv_event_t * e);
lv_obj_t *ui_TempSettingBack;
// CUSTOM VARIABLES


// SCREEN: ui_SystemSettingScreen
void ui_SystemSettingScreen_screen_init(void);
lv_obj_t *ui_SystemSettingScreen;
lv_obj_t *ui_SystemSettingHeader;
lv_obj_t *ui_ImageSystemHeader;
void ui_event_SystemSettingBack( lv_event_t * e);
lv_obj_t *ui_SystemSettingBack;
lv_obj_t *ui_SettingMenuDock;
void ui_event_CustomCurve( lv_event_t * e);
lv_obj_t *ui_CustomCurve;
lv_obj_t *ui_ImageCurve;
lv_obj_t *ui_TextCurve;
lv_obj_t *ui_PIDSetting;
lv_obj_t *ui_ImagePIDSetting;
lv_obj_t *ui_TextPIDSetting;
lv_obj_t *ui_TempLimited;
lv_obj_t *ui_ImageTempLimited;
void ui_event_SliderTempLimited( lv_event_t * e);
lv_obj_t *ui_SliderTempLimited;
lv_obj_t *ui_TextTempLimited;
lv_obj_t *ui_SleepTime;
lv_obj_t *ui_ImageSleepTime;
void ui_event_SliderSleepTime( lv_event_t * e);
lv_obj_t *ui_SliderSleepTime;
lv_obj_t *ui_TextSleepTime;
lv_obj_t *ui_Brightness;
lv_obj_t *ui_ImageBrightness;
void ui_event_SliderBrightness( lv_event_t * e);
lv_obj_t *ui_SliderBrightness;
lv_obj_t *ui_TextBrightness;
void ui_event_SaveConfig( lv_event_t * e);
lv_obj_t *ui_SaveConfig;
// CUSTOM VARIABLES


// SCREEN: ui_HeatingCurveScreen
void ui_HeatingCurveScreen_screen_init(void);
lv_obj_t *ui_HeatingCurveScreen;
lv_obj_t *ui_CustomCurveHeader;
lv_obj_t *ui_TextCurveHeader;
void ui_event_CustomCurveBack( lv_event_t * e);
lv_obj_t *ui_CustomCurveBack;
lv_obj_t *ui_CustomCurveDock;
lv_obj_t *ui_ProfileOne;
lv_obj_t *ui_ImageProfileOne;
void ui_event_SliderProfileOne( lv_event_t * e);
lv_obj_t *ui_SliderProfileOne;
lv_obj_t *ui_TextProfileOne;
void ui_event_SliderTimeOne( lv_event_t * e);
lv_obj_t *ui_SliderTimeOne;
lv_obj_t *ui_TextTimeOne;
lv_obj_t *ui_ProfileTwo;
lv_obj_t *ui_ImageProfileTwo;
void ui_event_SliderProfileTwo( lv_event_t * e);
lv_obj_t *ui_SliderProfileTwo;
lv_obj_t *ui_TextProfileTwo;
void ui_event_SliderTimeTwo( lv_event_t * e);
lv_obj_t *ui_SliderTimeTwo;
lv_obj_t *ui_TextTimeTwo;
lv_obj_t *ui_ProfileThree;
lv_obj_t *ui_ImageProfileThree;
void ui_event_SliderProfileThree( lv_event_t * e);
lv_obj_t *ui_SliderProfileThree;
lv_obj_t *ui_TextProfileThree;
void ui_event_SliderTimeThree( lv_event_t * e);
lv_obj_t *ui_SliderTimeThree;
lv_obj_t *ui_TextTimeThree;
lv_obj_t *ui_ProfileFour;
lv_obj_t *ui_ImageProfileFour;
void ui_event_SliderProfileFour( lv_event_t * e);
lv_obj_t *ui_SliderProfileFour;
lv_obj_t *ui_TextProfileFour;
void ui_event_SliderTimeFour( lv_event_t * e);
lv_obj_t *ui_SliderTimeFour;
lv_obj_t *ui_TextTimeFour;
lv_obj_t *ui_ProfileFive;
lv_obj_t *ui_ImageProfileFive;
void ui_event_SliderProfileFive( lv_event_t * e);
lv_obj_t *ui_SliderProfileFive;
lv_obj_t *ui_TextProfileFive;
void ui_event_SliderTimeFive( lv_event_t * e);
lv_obj_t *ui_SliderTimeFive;
lv_obj_t *ui_TextTimeFive;
// CUSTOM VARIABLES


// SCREEN: ui_ChartScreen
void ui_ChartScreen_screen_init(void);
lv_obj_t *ui_ChartScreen;
lv_obj_t *ui_ChartHeader;
lv_obj_t *ui_ChartRoomTemp;
lv_obj_t *ui_TextChartRoomTemp;
lv_obj_t *ui_ImageChartRoomTemp;
lv_obj_t *ui_ChartBuzzerStatus;
lv_obj_t *ui_ImageChartClock;
lv_obj_t *ui_ChartMinute;
lv_obj_t *ui_ChartSecond;
lv_obj_t *ui_TextChartTime;
void ui_event_ChartScreenBack( lv_event_t * e);
lv_obj_t *ui_ChartScreenBack;
lv_obj_t *ui_ChartScreenDock;
lv_obj_t *ui_ChartTemp;
lv_obj_t *ui_TextChartTemp;
lv_obj_t *ui_TextChatTargetTemp;
lv_obj_t *ui_ChartTargetTemp;
void ui_event_ChartTempSet( lv_event_t * e);
lv_obj_t *ui_ChartTempSet;
void ui_event_ChartSwitch( lv_event_t * e);
lv_obj_t *ui_ChartSwitch;
lv_obj_t *ui_ChartDock;
lv_obj_t *ui_TempChart;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *ui_imgset_num[10] = {&ui_img_num0_png, &ui_img_num1_png, &ui_img_num2_png, &ui_img_num3_png, &ui_img_num4_png, &ui_img_num5_png, &ui_img_num6_png, &ui_img_num7_png, &ui_img_num8_png, &ui_img_num9_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_MainScreen_screen_init();
ui_TemperatureSettingScreen_screen_init();
ui_SystemSettingScreen_screen_init();
ui_HeatingCurveScreen_screen_init();
ui_ChartScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_MainScreen);
}
