// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void FanTurnON(lv_event_t * e);
void FanTurnOFF(lv_event_t * e);
void HeatingStart(lv_event_t * e);
void HeatingStop(lv_event_t * e);
void SaveConfig(lv_event_t * e);
void PIDCalibrationStart(lv_event_t * e);
void PIDCalibrationStop(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
