// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"

void HeatingStart(lv_event_t * e)
{
	// Your code here
}

void HeatingStop(lv_event_t * e)
{
	// Your code here
}

void PIDCalibrationStart(lv_event_t * e)
{
	// Your code here
}

void PIDCalibrationStop(lv_event_t * e)
{
	// Your code here
}

void SaveConfig(lv_event_t * e)
{
	// Your code here
}

void FanTurnON(lv_event_t * e)
{
	// Your code here
}

void FanTurnOFF(lv_event_t * e)
{
	// Your code here
}
