// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void FanTurnON(lv_event_t * e);
void FanTurnOFF(lv_event_t * e);
void HeatingStart(lv_event_t * e);
void HeatingStop(lv_event_t * e);
void SaveConfig(lv_event_t * e);
void ChartHeaterStart(lv_event_t * e);
void ChartHeaterStop(lv_event_t * e);
void KpUpdate(lv_event_t * e);
void KiUpdate(lv_event_t * e);
void KdUpdate(lv_event_t * e);
void PIDKPMinus(lv_event_t * e);
void PIDKPPlus(lv_event_t * e);
void PIDKIMinus(lv_event_t * e);
void PIDKIPlus(lv_event_t * e);
void PIDKDMinus(lv_event_t * e);
void PIDKDPlus(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
