// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: HeatPlate

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Setting = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Setting, 50);
    lv_obj_set_height(ui_Setting, 50);
    lv_obj_set_x(ui_Setting, -5);
    lv_obj_set_y(ui_Setting, 5);
    lv_obj_set_align(ui_Setting, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_Setting, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Setting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Setting, lv_color_hex(0x00DEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Setting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_Setting, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Setting, lv_color_hex(0x00FF80), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Setting, 255, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_Image6 = lv_img_create(ui_Setting);
    lv_img_set_src(ui_Image6, &ui_img_setting_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image6, 60);

    ui_SET1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_SET1, 50);
    lv_obj_set_height(ui_SET1, 50);
    lv_obj_set_x(ui_SET1, -5);
    lv_obj_set_y(ui_SET1, 65);
    lv_obj_set_align(ui_SET1, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_SET1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SET1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SET1, lv_color_hex(0x00FF80), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SET1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_SET1, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_SET1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "SET1");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_SarasaMonoASCII18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SET2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_SET2, 50);
    lv_obj_set_height(ui_SET2, 50);
    lv_obj_set_x(ui_SET2, -5);
    lv_obj_set_y(ui_SET2, 125);
    lv_obj_set_align(ui_SET2, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_SET2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SET2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SET2, lv_color_hex(0x00FF80), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SET2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_SET2, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label2 = lv_label_create(ui_SET2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "SET2");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_SarasaMonoASCII18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SET3 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_SET3, 50);
    lv_obj_set_height(ui_SET3, 50);
    lv_obj_set_x(ui_SET3, -5);
    lv_obj_set_y(ui_SET3, 185);
    lv_obj_set_align(ui_SET3, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_SET3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SET3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SET3, lv_color_hex(0x00FF80), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SET3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_SET3, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label3 = lv_label_create(ui_SET3);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "SET3");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_SarasaMonoASCII18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 50);
    lv_obj_set_height(ui_Panel1, 170);
    lv_obj_set_x(ui_Panel1, 55);
    lv_obj_set_y(ui_Panel1, 65);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_TOP_RIGHT);
    lv_obj_set_scrollbar_mode(ui_Panel1, LV_SCROLLBAR_MODE_OFF);
    lv_obj_set_scroll_dir(ui_Panel1, LV_DIR_VER);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x00DEFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SET5 = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_SET5, 40);
    lv_obj_set_height(ui_SET5, 40);
    lv_obj_set_x(ui_SET5, 0);
    lv_obj_set_y(ui_SET5, -10);
    lv_obj_set_align(ui_SET5, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_SET5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SET5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SET5, lv_color_hex(0x00FF80), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SET5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_SET5, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SET6 = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_SET6, 40);
    lv_obj_set_height(ui_SET6, 40);
    lv_obj_set_x(ui_SET6, 0);
    lv_obj_set_y(ui_SET6, 35);
    lv_obj_set_align(ui_SET6, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_SET6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SET6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SET6, lv_color_hex(0x00FF80), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SET6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_SET6, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SET7 = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_SET7, 40);
    lv_obj_set_height(ui_SET7, 40);
    lv_obj_set_x(ui_SET7, 0);
    lv_obj_set_y(ui_SET7, 80);
    lv_obj_set_align(ui_SET7, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_SET7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SET7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SET7, lv_color_hex(0x00FF80), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SET7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_SET7, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SET8 = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_SET8, 40);
    lv_obj_set_height(ui_SET8, 40);
    lv_obj_set_x(ui_SET8, 0);
    lv_obj_set_y(ui_SET8, 125);
    lv_obj_set_align(ui_SET8, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_SET8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SET8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SET8, lv_color_hex(0x00FF80), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SET8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_SET8, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SET9 = lv_btn_create(ui_Panel1);
    lv_obj_set_width(ui_SET9, 40);
    lv_obj_set_height(ui_SET9, 40);
    lv_obj_set_x(ui_SET9, 0);
    lv_obj_set_y(ui_SET9, 170);
    lv_obj_set_align(ui_SET9, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_SET9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SET9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_SET9, lv_color_hex(0x00FF80), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SET9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_SET9, false, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Setting, ui_event_Setting, LV_EVENT_ALL, NULL);

}
