// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StatusHeader = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_StatusHeader);
lv_obj_set_width( ui_StatusHeader, 312);
lv_obj_set_height( ui_StatusHeader, 20);
lv_obj_set_x( ui_StatusHeader, 4 );
lv_obj_set_y( ui_StatusHeader, 2 );
lv_obj_clear_flag( ui_StatusHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_StatusHeader, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_StatusHeader, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StatusHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomTemp = lv_label_create(ui_StatusHeader);
lv_obj_set_width( ui_RoomTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomTemp, 20 );
lv_obj_set_y( ui_RoomTemp, 0 );
lv_obj_set_align( ui_RoomTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_RoomTemp,"00.00");
ui_object_set_themeable_style_property(ui_RoomTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_RoomTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_RoomTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextRoomTemp = lv_label_create(ui_StatusHeader);
lv_obj_set_width( ui_TextRoomTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextRoomTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextRoomTemp, 60 );
lv_obj_set_y( ui_TextRoomTemp, 0 );
lv_obj_set_align( ui_TextRoomTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextRoomTemp,"℃");
ui_object_set_themeable_style_property(ui_TextRoomTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextRoomTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextRoomTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageRoomTemp = lv_img_create(ui_StatusHeader);
lv_img_set_src(ui_ImageRoomTemp, &ui_img_740489818);
lv_obj_set_width( ui_ImageRoomTemp, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_ImageRoomTemp, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_ImageRoomTemp, -5 );
lv_obj_set_y( ui_ImageRoomTemp, 0 );
lv_obj_set_align( ui_ImageRoomTemp, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageRoomTemp, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageRoomTemp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageRoomTemp,128);

ui_BuzzerStatus = lv_img_create(ui_StatusHeader);
lv_img_set_src(ui_BuzzerStatus, &ui_img_1699618864);
lv_obj_set_width( ui_BuzzerStatus, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_BuzzerStatus, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_BuzzerStatus, 5 );
lv_obj_set_y( ui_BuzzerStatus, 0 );
lv_obj_set_align( ui_BuzzerStatus, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_BuzzerStatus, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BuzzerStatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_BuzzerStatus,128);

ui_ImageClock = lv_img_create(ui_StatusHeader);
lv_img_set_src(ui_ImageClock, &ui_img_290686881);
lv_obj_set_width( ui_ImageClock, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_ImageClock, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_ImageClock, 70 );
lv_obj_set_y( ui_ImageClock, 0 );
lv_obj_set_align( ui_ImageClock, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageClock, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageClock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageClock,128);

ui_Image1 = lv_img_create(ui_StatusHeader);
lv_img_set_src(ui_Image1, &ui_img_1205510230);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_Image1, 135 );
lv_obj_set_y( ui_Image1, 0 );
lv_obj_set_align( ui_Image1, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image1,128);

ui_Minute = lv_label_create(ui_StatusHeader);
lv_obj_set_width( ui_Minute, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Minute, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Minute, 95 );
lv_obj_set_y( ui_Minute, 0 );
lv_obj_set_align( ui_Minute, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Minute,"00");
ui_object_set_themeable_style_property(ui_Minute, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_Minute, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_Minute, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Second = lv_label_create(ui_StatusHeader);
lv_obj_set_width( ui_Second, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Second, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Second, 119 );
lv_obj_set_y( ui_Second, 0 );
lv_obj_set_align( ui_Second, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Second,"00");
ui_object_set_themeable_style_property(ui_Second, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_Second, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_Second, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextTime = lv_label_create(ui_StatusHeader);
lv_obj_set_width( ui_TextTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextTime, 111 );
lv_obj_set_y( ui_TextTime, 0 );
lv_obj_set_align( ui_TextTime, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextTime,":");
ui_object_set_themeable_style_property(ui_TextTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextTime, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeatingMode = lv_label_create(ui_StatusHeader);
lv_obj_set_width( ui_HeatingMode, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HeatingMode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeatingMode, 160 );
lv_obj_set_y( ui_HeatingMode, 0 );
lv_obj_set_align( ui_HeatingMode, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_HeatingMode,"Thermostatic");
ui_object_set_themeable_style_property(ui_HeatingMode, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_HeatingMode, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_HeatingMode, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeaterDock = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_HeaterDock);
lv_obj_set_width( ui_HeaterDock, 210);
lv_obj_set_height( ui_HeaterDock, 72);
lv_obj_set_x( ui_HeaterDock, 4 );
lv_obj_set_y( ui_HeaterDock, 28 );
lv_obj_clear_flag( ui_HeaterDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeaterDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeaterDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeaterDock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageHeater = lv_img_create(ui_HeaterDock);
lv_img_set_src(ui_ImageHeater, &ui_img_1956478733);
lv_obj_set_width( ui_ImageHeater, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_ImageHeater, LV_SIZE_CONTENT);   /// 64
lv_obj_set_x( ui_ImageHeater, 4 );
lv_obj_set_y( ui_ImageHeater, 0 );
lv_obj_set_align( ui_ImageHeater, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageHeater, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageHeater, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageHeater,300);

ui_HeatTemp = lv_label_create(ui_HeaterDock);
lv_obj_set_width( ui_HeatTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HeatTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeatTemp, 66 );
lv_obj_set_y( ui_HeatTemp, -8 );
lv_obj_set_align( ui_HeatTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_HeatTemp,"000");
ui_object_set_themeable_style_property(ui_HeatTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_HeatTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_HeatTemp, &ui_font_ASCII48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextHeatTemp = lv_label_create(ui_HeaterDock);
lv_obj_set_width( ui_TextHeatTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextHeatTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextHeatTemp, 140 );
lv_obj_set_y( ui_TextHeatTemp, -8 );
lv_obj_set_align( ui_TextHeatTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextHeatTemp,"℃");
ui_object_set_themeable_style_property(ui_TextHeatTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextHeatTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextHeatTemp, &ui_font_ASCII48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextTargetTemp = lv_label_create(ui_HeaterDock);
lv_obj_set_width( ui_TextTargetTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextTargetTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextTargetTemp, 68 );
lv_obj_set_y( ui_TextTargetTemp, 22 );
lv_obj_set_align( ui_TextTargetTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextTargetTemp,"TARGET:    ℃");
ui_object_set_themeable_style_property(ui_TextTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextTargetTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TargetTemp = lv_label_create(ui_HeaterDock);
lv_obj_set_width( ui_TargetTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TargetTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TargetTemp, 128 );
lv_obj_set_y( ui_TargetTemp, 22 );
lv_obj_set_align( ui_TargetTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TargetTemp,"000");
ui_object_set_themeable_style_property(ui_TargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TargetTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempSet = lv_btn_create(ui_HeaterDock);
lv_obj_set_width( ui_TempSet, 32);
lv_obj_set_height( ui_TempSet, 66);
lv_obj_set_x( ui_TempSet, -3 );
lv_obj_set_y( ui_TempSet, 3 );
lv_obj_set_align( ui_TempSet, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_TempSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_TempSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TempSet, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TempSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TempSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_TempSet, &ui_img_155116563, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_TempSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_TempSet, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FanDock = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_FanDock);
lv_obj_set_width( ui_FanDock, 210);
lv_obj_set_height( ui_FanDock, 72);
lv_obj_set_x( ui_FanDock, 4 );
lv_obj_set_y( ui_FanDock, 108 );
lv_obj_clear_flag( ui_FanDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_FanDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_FanDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FanDock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageFan = lv_img_create(ui_FanDock);
lv_img_set_src(ui_ImageFan, &ui_img_1162706898);
lv_obj_set_width( ui_ImageFan, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_ImageFan, LV_SIZE_CONTENT);   /// 64
lv_obj_set_x( ui_ImageFan, 4 );
lv_obj_set_y( ui_ImageFan, 0 );
lv_obj_set_align( ui_ImageFan, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageFan, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageFan, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_angle(ui_ImageFan,400);
lv_img_set_zoom(ui_ImageFan,300);

ui_FanPercent = lv_label_create(ui_FanDock);
lv_obj_set_width( ui_FanPercent, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FanPercent, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FanPercent, 66 );
lv_obj_set_y( ui_FanPercent, 0 );
lv_obj_set_align( ui_FanPercent, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_FanPercent,"000");
ui_object_set_themeable_style_property(ui_FanPercent, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_FanPercent, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_FanPercent, &ui_font_ASCII48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextFanPercent = lv_label_create(ui_FanDock);
lv_obj_set_width( ui_TextFanPercent, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextFanPercent, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextFanPercent, 140 );
lv_obj_set_y( ui_TextFanPercent, 0 );
lv_obj_set_align( ui_TextFanPercent, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextFanPercent,"%");
ui_object_set_themeable_style_property(ui_TextFanPercent, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextFanPercent, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextFanPercent, &ui_font_ASCII48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FanUP = lv_btn_create(ui_FanDock);
lv_obj_set_width( ui_FanUP, 32);
lv_obj_set_height( ui_FanUP, 32);
lv_obj_set_x( ui_FanUP, -3 );
lv_obj_set_y( ui_FanUP, 3 );
lv_obj_set_align( ui_FanUP, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_FanUP, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_FanUP, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_FanUP, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_FanUP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FanUP, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_FanUP, &ui_img_1345483443, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_FanUP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_FanUP, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FanDown = lv_btn_create(ui_FanDock);
lv_obj_set_width( ui_FanDown, 32);
lv_obj_set_height( ui_FanDown, 32);
lv_obj_set_x( ui_FanDown, -3 );
lv_obj_set_y( ui_FanDown, 37 );
lv_obj_set_align( ui_FanDown, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_FanDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_FanDown, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_FanDown, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_FanDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FanDown, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_FanDown, &ui_img_817906860, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_FanDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_FanDown, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_USER1 = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_USER1, 32);
lv_obj_set_height( ui_USER1, 32);
lv_obj_set_x( ui_USER1, -4 );
lv_obj_set_y( ui_USER1, 28 );
lv_obj_set_align( ui_USER1, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_USER1, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_USER1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_USER1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_USER1, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_USER1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_USER1, &ui_img_1577463476, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_USER1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_USER1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_USER1, &ui_img_1577463476, LV_PART_MAIN | LV_STATE_PRESSED );
ui_object_set_themeable_style_property(ui_USER1, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_USER1, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_ButtonPressed);

ui_USER2 = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_USER2, 32);
lv_obj_set_height( ui_USER2, 32);
lv_obj_set_x( ui_USER2, -4 );
lv_obj_set_y( ui_USER2, 68 );
lv_obj_set_align( ui_USER2, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_USER2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_USER2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_USER2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_USER2, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_USER2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_USER2, &ui_img_1006688281, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_USER2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_USER2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_USER2, &ui_img_1006688281, LV_PART_MAIN | LV_STATE_PRESSED );
ui_object_set_themeable_style_property(ui_USER2, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_USER2, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_ButtonPressed);

ui_USER3 = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_USER3, 32);
lv_obj_set_height( ui_USER3, 32);
lv_obj_set_x( ui_USER3, -4 );
lv_obj_set_y( ui_USER3, 108 );
lv_obj_set_align( ui_USER3, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_USER3, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_USER3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_USER3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_USER3, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_USER3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_USER3, &ui_img_1428031618, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_USER3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_USER3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_USER3, &ui_img_1428031618, LV_PART_MAIN | LV_STATE_PRESSED );
ui_object_set_themeable_style_property(ui_USER3, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_USER3, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_ButtonPressed);

ui_USER4 = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_USER4, 32);
lv_obj_set_height( ui_USER4, 32);
lv_obj_set_x( ui_USER4, -4 );
lv_obj_set_y( ui_USER4, 148 );
lv_obj_set_align( ui_USER4, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_USER4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_USER4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_USER4, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_USER4, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_USER4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_USER4, &ui_img_1680627741, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_img_tiled(ui_USER4, false, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_USER4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_USER4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_USER4, &ui_img_1680627741, LV_PART_MAIN | LV_STATE_PRESSED );
ui_object_set_themeable_style_property(ui_USER4, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_USER4, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_ButtonPressed);

ui_Setting = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_Setting, 96);
lv_obj_set_height( ui_Setting, 44);
lv_obj_set_x( ui_Setting, -4 );
lv_obj_set_y( ui_Setting, 188 );
lv_obj_set_align( ui_Setting, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_Setting, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Setting, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Setting, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Setting, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Setting, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Setting, &ui_img_1671917170, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_Setting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Setting, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BuzzerSwitch = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_BuzzerSwitch, 100);
lv_obj_set_height( ui_BuzzerSwitch, 44);
lv_obj_set_x( ui_BuzzerSwitch, -106 );
lv_obj_set_y( ui_BuzzerSwitch, 188 );
lv_obj_set_align( ui_BuzzerSwitch, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_BuzzerSwitch, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BuzzerSwitch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BuzzerSwitch, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_BuzzerSwitch, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_BuzzerSwitch, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonPressed);
lv_obj_set_style_bg_img_src( ui_BuzzerSwitch, &ui_img_185202102, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_BuzzerSwitch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BuzzerSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_BuzzerSwitch, 5, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_BuzzerSwitch, &ui_img_1699618864, LV_PART_MAIN | LV_STATE_CHECKED );

ui_FanSwitch = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_FanSwitch, 100);
lv_obj_set_height( ui_FanSwitch, 44);
lv_obj_set_x( ui_FanSwitch, -216 );
lv_obj_set_y( ui_FanSwitch, 188 );
lv_obj_set_align( ui_FanSwitch, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_FanSwitch, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_FanSwitch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_FanSwitch, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_FanSwitch, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_FanSwitch, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonPressed);
lv_obj_set_style_bg_img_src( ui_FanSwitch, &ui_img_2103744591, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_FanSwitch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_FanSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_FanSwitch, 5, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_FanSwitch, &ui_img_1708415670, LV_PART_MAIN | LV_STATE_CHECKED );

ui_StartStop = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_StartStop, 56);
lv_obj_set_height( ui_StartStop, 152);
lv_obj_set_x( ui_StartStop, 220 );
lv_obj_set_y( ui_StartStop, 28 );
lv_obj_add_flag( ui_StartStop, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_StartStop, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_StartStop, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_StartStop, lv_color_hex(0x00FF8C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StartStop, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_StartStop, &ui_img_1347724781, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_StartStop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_StartStop, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_StartStop, &ui_img_413634367, LV_PART_MAIN | LV_STATE_CHECKED );

lv_obj_add_event_cb(ui_TempSet, ui_event_TempSet, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_FanUP, ui_event_FanUP, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_FanDown, ui_event_FanDown, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_USER1, ui_event_USER1, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_USER2, ui_event_USER2, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_USER3, ui_event_USER3, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_USER4, ui_event_USER4, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Setting, ui_event_Setting, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BuzzerSwitch, ui_event_BuzzerSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_FanSwitch, ui_event_FanSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_StartStop, ui_event_StartStop, LV_EVENT_ALL, NULL);

}
