// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#include "../ui.h"

void ui_PIDCalibrationScreen_screen_init(void)
{
ui_PIDCalibrationScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_PIDCalibrationScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_PIDCalibrationScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_PIDCalibrationScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);

ui_PIDCalibrationHeader = lv_obj_create(ui_PIDCalibrationScreen);
lv_obj_remove_style_all(ui_PIDCalibrationHeader);
lv_obj_set_width( ui_PIDCalibrationHeader, 316);
lv_obj_set_height( ui_PIDCalibrationHeader, 20);
lv_obj_set_x( ui_PIDCalibrationHeader, 0 );
lv_obj_set_y( ui_PIDCalibrationHeader, 2 );
lv_obj_set_align( ui_PIDCalibrationHeader, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_PIDCalibrationHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PIDCalibrationHeader, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PIDCalibrationHeader, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PIDCalibrationHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextPIDHeader = lv_label_create(ui_PIDCalibrationHeader);
lv_obj_set_width( ui_TextPIDHeader, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextPIDHeader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextPIDHeader, 0 );
lv_obj_set_y( ui_TextPIDHeader, -1 );
lv_obj_set_align( ui_TextPIDHeader, LV_ALIGN_CENTER );
lv_label_set_text(ui_TextPIDHeader,"PID Calibration");
ui_object_set_themeable_style_property(ui_TextPIDHeader, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextPIDHeader, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextPIDHeader, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PIDCalibrationBack = lv_btn_create(ui_PIDCalibrationScreen);
lv_obj_set_width( ui_PIDCalibrationBack, 32);
lv_obj_set_height( ui_PIDCalibrationBack, 212);
lv_obj_set_x( ui_PIDCalibrationBack, -286 );
lv_obj_set_y( ui_PIDCalibrationBack, 25 );
lv_obj_set_align( ui_PIDCalibrationBack, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_PIDCalibrationBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PIDCalibrationBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PIDCalibrationBack, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PIDCalibrationBack, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PIDCalibrationBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_PIDCalibrationBack, &ui_img_852573520, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_PIDCalibrationBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_PIDCalibrationBack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PIDCalibrationDock = lv_obj_create(ui_PIDCalibrationScreen);
lv_obj_remove_style_all(ui_PIDCalibrationDock);
lv_obj_set_width( ui_PIDCalibrationDock, 282);
lv_obj_set_height( ui_PIDCalibrationDock, 64);
lv_obj_set_x( ui_PIDCalibrationDock, 36 );
lv_obj_set_y( ui_PIDCalibrationDock, 25 );
lv_obj_clear_flag( ui_PIDCalibrationDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PIDCalibrationDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_PIDCalibrationDock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_PIDCalibrationDock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);

ui_ImageHeaterPID = lv_img_create(ui_PIDCalibrationDock);
lv_img_set_src(ui_ImageHeaterPID, &ui_img_1956478733);
lv_obj_set_width( ui_ImageHeaterPID, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_ImageHeaterPID, LV_SIZE_CONTENT);   /// 64
lv_obj_set_x( ui_ImageHeaterPID, 4 );
lv_obj_set_y( ui_ImageHeaterPID, 0 );
lv_obj_set_align( ui_ImageHeaterPID, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageHeaterPID, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageHeaterPID, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageHeaterPID,300);

ui_PIDCurrentTemp = lv_label_create(ui_PIDCalibrationDock);
lv_obj_set_width( ui_PIDCurrentTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PIDCurrentTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PIDCurrentTemp, 66 );
lv_obj_set_y( ui_PIDCurrentTemp, -8 );
lv_obj_set_align( ui_PIDCurrentTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_PIDCurrentTemp,"000");
ui_object_set_themeable_style_property(ui_PIDCurrentTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_PIDCurrentTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_PIDCurrentTemp, &ui_font_ASCII48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextPIDTemp = lv_label_create(ui_PIDCalibrationDock);
lv_obj_set_width( ui_TextPIDTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextPIDTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextPIDTemp, 140 );
lv_obj_set_y( ui_TextPIDTemp, -8 );
lv_obj_set_align( ui_TextPIDTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextPIDTemp,"℃");
ui_object_set_themeable_style_property(ui_TextPIDTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextPIDTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextPIDTemp, &ui_font_ASCII48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextPIDTargetTemp = lv_label_create(ui_PIDCalibrationDock);
lv_obj_set_width( ui_TextPIDTargetTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextPIDTargetTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextPIDTargetTemp, 68 );
lv_obj_set_y( ui_TextPIDTargetTemp, 22 );
lv_obj_set_align( ui_TextPIDTargetTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextPIDTargetTemp,"TARGET:    ℃");
ui_object_set_themeable_style_property(ui_TextPIDTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextPIDTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextPIDTargetTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PIDTargetTemp = lv_label_create(ui_PIDCalibrationDock);
lv_obj_set_width( ui_PIDTargetTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_PIDTargetTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_PIDTargetTemp, 128 );
lv_obj_set_y( ui_PIDTargetTemp, 22 );
lv_obj_set_align( ui_PIDTargetTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_PIDTargetTemp,"000");
ui_object_set_themeable_style_property(ui_PIDTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_PIDTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_PIDTargetTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PIDTempSet = lv_btn_create(ui_PIDCalibrationDock);
lv_obj_set_width( ui_PIDTempSet, 32);
lv_obj_set_height( ui_PIDTempSet, 60);
lv_obj_set_x( ui_PIDTempSet, 175 );
lv_obj_set_y( ui_PIDTempSet, 0 );
lv_obj_set_align( ui_PIDTempSet, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_PIDTempSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PIDTempSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PIDTempSet, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PIDTempSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PIDTempSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_PIDTempSet, &ui_img_155116563, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_PIDTempSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_PIDTempSet, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PIDCalibrationSwitch = lv_btn_create(ui_PIDCalibrationDock);
lv_obj_set_width( ui_PIDCalibrationSwitch, 64);
lv_obj_set_height( ui_PIDCalibrationSwitch, 60);
lv_obj_set_x( ui_PIDCalibrationSwitch, 216 );
lv_obj_set_y( ui_PIDCalibrationSwitch, 2 );
lv_obj_add_flag( ui_PIDCalibrationSwitch, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PIDCalibrationSwitch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PIDCalibrationSwitch, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PIDCalibrationSwitch, lv_color_hex(0x00FF8C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PIDCalibrationSwitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_PIDCalibrationSwitch, &ui_img_1347724781, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_PIDCalibrationSwitch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_PIDCalibrationSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_PIDCalibrationSwitch, &ui_img_413634367, LV_PART_MAIN | LV_STATE_CHECKED );

ui_PIDChartDock = lv_obj_create(ui_PIDCalibrationScreen);
lv_obj_remove_style_all(ui_PIDChartDock);
lv_obj_set_width( ui_PIDChartDock, 282);
lv_obj_set_height( ui_PIDChartDock, 146);
lv_obj_set_x( ui_PIDChartDock, 36 );
lv_obj_set_y( ui_PIDChartDock, 91 );
lv_obj_clear_flag( ui_PIDChartDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PIDChartDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_PIDChartDock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_PIDChartDock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);

ui_TempChart = lv_chart_create(ui_PIDChartDock);
lv_obj_set_width( ui_TempChart, 247);
lv_obj_set_height( ui_TempChart, 142);
lv_obj_set_x( ui_TempChart, 18 );
lv_obj_set_y( ui_TempChart, 2 );
lv_chart_set_type( ui_TempChart, LV_CHART_TYPE_LINE);
lv_chart_set_range( ui_TempChart, LV_CHART_AXIS_PRIMARY_Y, 0, 450);
lv_chart_set_div_line_count( ui_TempChart, 10, 0);
lv_chart_set_axis_tick( ui_TempChart, LV_CHART_AXIS_PRIMARY_X, 0, 0, 64, 0, false, 50);
lv_chart_set_axis_tick( ui_TempChart, LV_CHART_AXIS_PRIMARY_Y, 1, 0, 10, 1, true, 50);
lv_chart_set_axis_tick( ui_TempChart, LV_CHART_AXIS_SECONDARY_Y, 1, 0, 10, 1, true, 0);
lv_chart_series_t* ui_TempChart_series_1 = lv_chart_add_series(ui_TempChart, lv_color_hex(0xFF0000), LV_CHART_AXIS_PRIMARY_Y);
static lv_coord_t ui_TempChart_series_1_array[] = { 10,20,30,40,50,60,70,80,90,100 };
lv_chart_set_ext_y_array(ui_TempChart, ui_TempChart_series_1, ui_TempChart_series_1_array);
lv_chart_series_t* ui_TempChart_series_2 = lv_chart_add_series(ui_TempChart, lv_color_hex(0x00E8FF), LV_CHART_AXIS_SECONDARY_Y);
static lv_coord_t ui_TempChart_series_2_array[] = { 0,10,20,40,80,80,40,80,90,100 };
lv_chart_set_ext_y_array(ui_TempChart, ui_TempChart_series_2, ui_TempChart_series_2_array);
ui_object_set_themeable_style_property(ui_TempChart, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TempChart, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_TextAndImage);


lv_obj_set_style_size(ui_TempChart, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_object_set_themeable_style_property(ui_TempChart, LV_PART_TICKS| LV_STATE_DEFAULT, LV_STYLE_LINE_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TempChart, LV_PART_TICKS| LV_STATE_DEFAULT, LV_STYLE_LINE_OPA, _ui_theme_alpha_TextAndImage);
ui_object_set_themeable_style_property(ui_TempChart, LV_PART_TICKS| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TempChart, LV_PART_TICKS| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TempChart, &ui_font_Chart, LV_PART_TICKS| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_PIDCalibrationBack, ui_event_PIDCalibrationBack, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PIDTempSet, ui_event_PIDTempSet, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PIDCalibrationSwitch, ui_event_PIDCalibrationSwitch, LV_EVENT_ALL, NULL);

}
