// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#include "../ui.h"

void ui_SystemSetting_screen_init(void)
{
ui_SystemSetting = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SystemSetting, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_SystemSetting, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_SystemSetting, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);

ui_SystemSettingDock = lv_obj_create(ui_SystemSetting);
lv_obj_remove_style_all(ui_SystemSettingDock);
lv_obj_set_width( ui_SystemSettingDock, 316);
lv_obj_set_height( ui_SystemSettingDock, 20);
lv_obj_set_x( ui_SystemSettingDock, 0 );
lv_obj_set_y( ui_SystemSettingDock, 2 );
lv_obj_set_align( ui_SystemSettingDock, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_SystemSettingDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SystemSettingDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SystemSettingDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SystemSettingDock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_System_Setting = lv_label_create(ui_SystemSettingDock);
lv_obj_set_width( ui_System_Setting, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_System_Setting, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_System_Setting, 0 );
lv_obj_set_y( ui_System_Setting, -1 );
lv_obj_set_align( ui_System_Setting, LV_ALIGN_CENTER );
lv_label_set_text(ui_System_Setting,"System Setting");
ui_object_set_themeable_style_property(ui_System_Setting, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_System_Setting, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_System_Setting, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingBack = lv_btn_create(ui_SystemSetting);
lv_obj_set_width( ui_SettingBack, 32);
lv_obj_set_height( ui_SettingBack, 212);
lv_obj_set_x( ui_SettingBack, -286 );
lv_obj_set_y( ui_SettingBack, 25 );
lv_obj_set_align( ui_SettingBack, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_SettingBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SettingBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SettingBack, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SettingBack, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SettingBack, &ui_img_852573520, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_SettingBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_SettingBack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingMenuDock = lv_obj_create(ui_SystemSetting);
lv_obj_remove_style_all(ui_SettingMenuDock);
lv_obj_set_width( ui_SettingMenuDock, 281);
lv_obj_set_height( ui_SettingMenuDock, 212);
lv_obj_set_x( ui_SettingMenuDock, 36 );
lv_obj_set_y( ui_SettingMenuDock, 25 );
lv_obj_clear_flag( ui_SettingMenuDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SettingMenuDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SettingMenuDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingMenuDock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_SettingBack, ui_event_SettingBack, LV_EVENT_ALL, NULL);

}
