// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#include "../ui.h"

void ui_SystemSettingScreen_screen_init(void)
{
ui_SystemSettingScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SystemSettingScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_SystemSettingScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_SystemSettingScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);

ui_SystemSettingHeader = lv_obj_create(ui_SystemSettingScreen);
lv_obj_remove_style_all(ui_SystemSettingHeader);
lv_obj_set_width( ui_SystemSettingHeader, 316);
lv_obj_set_height( ui_SystemSettingHeader, 20);
lv_obj_set_x( ui_SystemSettingHeader, 0 );
lv_obj_set_y( ui_SystemSettingHeader, 2 );
lv_obj_set_align( ui_SystemSettingHeader, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_SystemSettingHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SystemSettingHeader, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SystemSettingHeader, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SystemSettingHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageSystemHeader = lv_label_create(ui_SystemSettingHeader);
lv_obj_set_width( ui_ImageSystemHeader, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageSystemHeader, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageSystemHeader, 0 );
lv_obj_set_y( ui_ImageSystemHeader, -1 );
lv_obj_set_align( ui_ImageSystemHeader, LV_ALIGN_CENTER );
lv_label_set_text(ui_ImageSystemHeader,"System Setting");
ui_object_set_themeable_style_property(ui_ImageSystemHeader, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_ImageSystemHeader, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_ImageSystemHeader, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SystemSettingBack = lv_btn_create(ui_SystemSettingScreen);
lv_obj_set_width( ui_SystemSettingBack, 32);
lv_obj_set_height( ui_SystemSettingBack, 212);
lv_obj_set_x( ui_SystemSettingBack, -286 );
lv_obj_set_y( ui_SystemSettingBack, 25 );
lv_obj_set_align( ui_SystemSettingBack, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_SystemSettingBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SystemSettingBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SystemSettingBack, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SystemSettingBack, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SystemSettingBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SystemSettingBack, &ui_img_852573520, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_SystemSettingBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_SystemSettingBack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingMenuDock = lv_obj_create(ui_SystemSettingScreen);
lv_obj_remove_style_all(ui_SettingMenuDock);
lv_obj_set_width( ui_SettingMenuDock, 281);
lv_obj_set_height( ui_SettingMenuDock, 212);
lv_obj_set_x( ui_SettingMenuDock, 36 );
lv_obj_set_y( ui_SettingMenuDock, 25 );
lv_obj_clear_flag( ui_SettingMenuDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SettingMenuDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SettingMenuDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingMenuDock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PIDCalibration = lv_btn_create(ui_SettingMenuDock);
lv_obj_set_width( ui_PIDCalibration, 190);
lv_obj_set_height( ui_PIDCalibration, 32);
lv_obj_set_x( ui_PIDCalibration, 4 );
lv_obj_set_y( ui_PIDCalibration, 4 );
lv_obj_add_flag( ui_PIDCalibration, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_PIDCalibration, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PIDCalibration, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_PIDCalibration, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_PIDCalibration, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);
lv_obj_set_style_shadow_color(ui_PIDCalibration, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_PIDCalibration, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_PIDCalibration, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_PIDCalibration, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_ButtonPressed);

ui_ImagePID = lv_img_create(ui_PIDCalibration);
lv_img_set_src(ui_ImagePID, &ui_img_329106951);
lv_obj_set_width( ui_ImagePID, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImagePID, LV_SIZE_CONTENT);   /// 32
lv_obj_set_align( ui_ImagePID, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImagePID, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImagePID, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TextPID = lv_label_create(ui_PIDCalibration);
lv_obj_set_width( ui_TextPID, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextPID, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextPID, 50 );
lv_obj_set_y( ui_TextPID, 0 );
lv_obj_set_align( ui_TextPID, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextPID,"PID Calibration");
ui_object_set_themeable_style_property(ui_TextPID, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextPID, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextPID, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_CustomCurve = lv_btn_create(ui_SettingMenuDock);
lv_obj_set_width( ui_CustomCurve, 190);
lv_obj_set_height( ui_CustomCurve, 32);
lv_obj_set_x( ui_CustomCurve, 4 );
lv_obj_set_y( ui_CustomCurve, 44 );
lv_obj_add_flag( ui_CustomCurve, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_CustomCurve, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_CustomCurve, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_CustomCurve, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_CustomCurve, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);
lv_obj_set_style_shadow_color(ui_CustomCurve, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_CustomCurve, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_CustomCurve, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_CustomCurve, LV_PART_MAIN| LV_STATE_PRESSED, LV_STYLE_BG_IMG_RECOLOR_OPA, _ui_theme_alpha_ButtonPressed);

ui_ImageCurve = lv_img_create(ui_CustomCurve);
lv_img_set_src(ui_ImageCurve, &ui_img_1205510230);
lv_obj_set_width( ui_ImageCurve, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageCurve, LV_SIZE_CONTENT);   /// 32
lv_obj_set_align( ui_ImageCurve, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageCurve, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageCurve, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TextCurve = lv_label_create(ui_CustomCurve);
lv_obj_set_width( ui_TextCurve, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextCurve, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextCurve, 50 );
lv_obj_set_y( ui_TextCurve, 0 );
lv_obj_set_align( ui_TextCurve, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextCurve,"Custom Curve");
ui_object_set_themeable_style_property(ui_TextCurve, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextCurve, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextCurve, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempLimited = lv_obj_create(ui_SettingMenuDock);
lv_obj_remove_style_all(ui_TempLimited);
lv_obj_set_width( ui_TempLimited, 273);
lv_obj_set_height( ui_TempLimited, 32);
lv_obj_set_x( ui_TempLimited, 4 );
lv_obj_set_y( ui_TempLimited, 84 );
lv_obj_clear_flag( ui_TempLimited, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TempLimited, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_TempLimited, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_TempLimited, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);

ui_ImageTempLimited = lv_img_create(ui_TempLimited);
lv_img_set_src(ui_ImageTempLimited, &ui_img_740489818);
lv_obj_set_width( ui_ImageTempLimited, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageTempLimited, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_ImageTempLimited, 13 );
lv_obj_set_y( ui_ImageTempLimited, 0 );
lv_obj_set_align( ui_ImageTempLimited, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageTempLimited, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageTempLimited, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SliderTempLimited = lv_slider_create(ui_TempLimited);
lv_slider_set_range(ui_SliderTempLimited, 0,400);
lv_slider_set_value( ui_SliderTempLimited, 400, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderTempLimited)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderTempLimited, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderTempLimited, 155);
lv_obj_set_height( ui_SliderTempLimited, 10);
lv_obj_set_x( ui_SliderTempLimited, 63 );
lv_obj_set_y( ui_SliderTempLimited, 0 );
lv_obj_set_align( ui_SliderTempLimited, LV_ALIGN_LEFT_MID );
ui_object_set_themeable_style_property(ui_SliderTempLimited, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_SliderTempLimited, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_TextAndImage);

ui_object_set_themeable_style_property(ui_SliderTempLimited, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_SliderTempLimited, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);

lv_obj_set_style_blend_mode(ui_SliderTempLimited, LV_BLEND_MODE_NORMAL, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_SliderTempLimited, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_TextTempLimited = lv_label_create(ui_TempLimited);
lv_obj_set_width( ui_TextTempLimited, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextTempLimited, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextTempLimited, -10 );
lv_obj_set_y( ui_TextTempLimited, 0 );
lv_obj_set_align( ui_TextTempLimited, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_TextTempLimited,"400℃");
ui_object_set_themeable_style_property(ui_TextTempLimited, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextTempLimited, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextTempLimited, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SleepTime = lv_obj_create(ui_SettingMenuDock);
lv_obj_remove_style_all(ui_SleepTime);
lv_obj_set_width( ui_SleepTime, 273);
lv_obj_set_height( ui_SleepTime, 32);
lv_obj_set_x( ui_SleepTime, 4 );
lv_obj_set_y( ui_SleepTime, 124 );
lv_obj_clear_flag( ui_SleepTime, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SleepTime, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_SleepTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_SleepTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);

ui_ImageSleepTime = lv_img_create(ui_SleepTime);
lv_img_set_src(ui_ImageSleepTime, &ui_img_295618317);
lv_obj_set_width( ui_ImageSleepTime, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageSleepTime, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_ImageSleepTime, 13 );
lv_obj_set_y( ui_ImageSleepTime, 0 );
lv_obj_set_align( ui_ImageSleepTime, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageSleepTime, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageSleepTime, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SliderSleepTime = lv_slider_create(ui_SleepTime);
lv_slider_set_range(ui_SliderSleepTime, 10,60);
lv_slider_set_value( ui_SliderSleepTime, 10, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderSleepTime)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderSleepTime, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderSleepTime, 155);
lv_obj_set_height( ui_SliderSleepTime, 10);
lv_obj_set_x( ui_SliderSleepTime, 63 );
lv_obj_set_y( ui_SliderSleepTime, 0 );
lv_obj_set_align( ui_SliderSleepTime, LV_ALIGN_LEFT_MID );
ui_object_set_themeable_style_property(ui_SliderSleepTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_SliderSleepTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_TextAndImage);

ui_object_set_themeable_style_property(ui_SliderSleepTime, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_SliderSleepTime, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);

lv_obj_set_style_blend_mode(ui_SliderSleepTime, LV_BLEND_MODE_NORMAL, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_SliderSleepTime, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_TextSleepTime = lv_label_create(ui_SleepTime);
lv_obj_set_width( ui_TextSleepTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextSleepTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextSleepTime, -10 );
lv_obj_set_y( ui_TextSleepTime, 0 );
lv_obj_set_align( ui_TextSleepTime, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_TextSleepTime,"10Min");
ui_object_set_themeable_style_property(ui_TextSleepTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextSleepTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextSleepTime, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Brightness = lv_obj_create(ui_SettingMenuDock);
lv_obj_remove_style_all(ui_Brightness);
lv_obj_set_width( ui_Brightness, 273);
lv_obj_set_height( ui_Brightness, 32);
lv_obj_set_x( ui_Brightness, 4 );
lv_obj_set_y( ui_Brightness, 164 );
lv_obj_clear_flag( ui_Brightness, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Brightness, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_Brightness, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_Brightness, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);

ui_ImageBrightness = lv_img_create(ui_Brightness);
lv_img_set_src(ui_ImageBrightness, &ui_img_637286161);
lv_obj_set_width( ui_ImageBrightness, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ImageBrightness, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_ImageBrightness, 13 );
lv_obj_set_y( ui_ImageBrightness, 0 );
lv_obj_set_align( ui_ImageBrightness, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageBrightness, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageBrightness, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SliderBrightness = lv_slider_create(ui_Brightness);
lv_slider_set_range(ui_SliderBrightness, 10,100);
lv_slider_set_value( ui_SliderBrightness, 50, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_SliderBrightness)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_SliderBrightness, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_SliderBrightness, 155);
lv_obj_set_height( ui_SliderBrightness, 10);
lv_obj_set_x( ui_SliderBrightness, 63 );
lv_obj_set_y( ui_SliderBrightness, 0 );
lv_obj_set_align( ui_SliderBrightness, LV_ALIGN_LEFT_MID );
ui_object_set_themeable_style_property(ui_SliderBrightness, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_SliderBrightness, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_TextAndImage);

ui_object_set_themeable_style_property(ui_SliderBrightness, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_SliderBrightness, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);

lv_obj_set_style_blend_mode(ui_SliderBrightness, LV_BLEND_MODE_NORMAL, LV_PART_KNOB| LV_STATE_DEFAULT);
lv_obj_set_style_opa(ui_SliderBrightness, 0, LV_PART_KNOB| LV_STATE_DEFAULT);

ui_TextBrightness = lv_label_create(ui_Brightness);
lv_obj_set_width( ui_TextBrightness, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextBrightness, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextBrightness, -10 );
lv_obj_set_y( ui_TextBrightness, 0 );
lv_obj_set_align( ui_TextBrightness, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_TextBrightness,"50%");
ui_object_set_themeable_style_property(ui_TextBrightness, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextBrightness, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextBrightness, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SaveConfig = lv_btn_create(ui_SettingMenuDock);
lv_obj_set_width( ui_SaveConfig, 72);
lv_obj_set_height( ui_SaveConfig, 72);
lv_obj_set_x( ui_SaveConfig, 205 );
lv_obj_set_y( ui_SaveConfig, 4 );
lv_obj_add_flag( ui_SaveConfig, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SaveConfig, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_SaveConfig, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SaveConfig, lv_color_hex(0x00FF8C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SaveConfig, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_SaveConfig, &ui_img_1723942165, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_SaveConfig, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_SaveConfig, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_SystemSettingBack, ui_event_SystemSettingBack, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_PIDCalibration, ui_event_PIDCalibration, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_CustomCurve, ui_event_CustomCurve, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SliderTempLimited, ui_event_SliderTempLimited, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SliderSleepTime, ui_event_SliderSleepTime, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SliderBrightness, ui_event_SliderBrightness, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SaveConfig, ui_event_SaveConfig, LV_EVENT_ALL, NULL);

}
