// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t *ui_MainScreen;
lv_obj_t *ui_StatusDock;
lv_obj_t *ui_Temp;
lv_obj_t *ui_TempC;
lv_obj_t *ui_TempPic;
lv_obj_t *ui_BuzzerStatus;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Hour;
lv_obj_t *ui_Minute;
lv_obj_t *ui_Second;
lv_obj_t *ui_Time1;
lv_obj_t *ui_Time2;
lv_obj_t *ui_HeatDock;
lv_obj_t *ui_HeatPic;
lv_obj_t *ui_HeatTemp;
lv_obj_t *ui_HeatTempC;
lv_obj_t *ui_Target;
lv_obj_t *ui_TargetTemp;
void ui_event_TempSet( lv_event_t * e);
lv_obj_t *ui_TempSet;
lv_obj_t *ui_FAN;
lv_obj_t *ui_FanPic;
lv_obj_t *ui_FanPercent;
lv_obj_t *ui_Percent;
void ui_event_FanUP( lv_event_t * e);
lv_obj_t *ui_FanUP;
void ui_event_FanDown( lv_event_t * e);
lv_obj_t *ui_FanDown;
void ui_event_USER1( lv_event_t * e);
lv_obj_t *ui_USER1;
void ui_event_USER2( lv_event_t * e);
lv_obj_t *ui_USER2;
void ui_event_USER3( lv_event_t * e);
lv_obj_t *ui_USER3;
void ui_event_USER4( lv_event_t * e);
lv_obj_t *ui_USER4;
void ui_event_Setting( lv_event_t * e);
lv_obj_t *ui_Setting;
lv_obj_t *ui_StartStop;
// CUSTOM VARIABLES


// SCREEN: ui_TemperatureSetting
void ui_TemperatureSetting_screen_init(void);
lv_obj_t *ui_TemperatureSetting;
lv_obj_t *ui_Keyboard;
void ui_event_Confirm( lv_event_t * e);
lv_obj_t *ui_Confirm;
void ui_event_Delete( lv_event_t * e);
lv_obj_t *ui_Delete;
void ui_event_Num0( lv_event_t * e);
lv_obj_t *ui_Num0;
lv_obj_t *ui_Panel2;
void ui_event_Num1( lv_event_t * e);
lv_obj_t *ui_Num1;
void ui_event_Num2( lv_event_t * e);
lv_obj_t *ui_Num2;
void ui_event_Num3( lv_event_t * e);
lv_obj_t *ui_Num3;
void ui_event_Num4( lv_event_t * e);
lv_obj_t *ui_Num4;
void ui_event_Num5( lv_event_t * e);
lv_obj_t *ui_Num5;
void ui_event_Num6( lv_event_t * e);
lv_obj_t *ui_Num6;
void ui_event_Num7( lv_event_t * e);
lv_obj_t *ui_Num7;
void ui_event_Num8( lv_event_t * e);
lv_obj_t *ui_Num8;
void ui_event_Num9( lv_event_t * e);
lv_obj_t *ui_Num9;
lv_obj_t *ui_TempSettingDock;
lv_obj_t *ui_TempSetting;
lv_obj_t *ui_HeatDock2;
lv_obj_t *ui_Heatpic;
lv_obj_t *ui_SetTemp;
lv_obj_t *ui_SetTempC;
lv_obj_t *ui_Current;
lv_obj_t *ui_CurrentTemp;
// CUSTOM VARIABLES


// SCREEN: ui_SystemSetting
void ui_SystemSetting_screen_init(void);
lv_obj_t *ui_SystemSetting;
lv_obj_t *ui_SystemSettingDock;
lv_obj_t *ui_System_Setting;
void ui_event_SettingBack( lv_event_t * e);
lv_obj_t *ui_SettingBack;
lv_obj_t *ui_SettingMenuDock;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////


void ui_event_SettingBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_MainScreen_screen_init);
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_MainScreen_screen_init();
ui_TemperatureSetting_screen_init();
ui_SystemSetting_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_MainScreen);
}
