// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#ifndef _UI_UI_H
#define _UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t * ui_MainScreen;
extern lv_obj_t * ui_StatusDock;
extern lv_obj_t * ui_Temp;
extern lv_obj_t * ui_TempC;
extern lv_obj_t * ui_TempPic;
extern lv_obj_t * ui_BuzzerStatus;
extern lv_obj_t * ui_HeatDock;
extern lv_obj_t * ui_HeatPic;
extern lv_obj_t * ui_HeatTemp;
extern lv_obj_t * ui_HeatTempC;
extern lv_obj_t * ui_Target;
extern lv_obj_t * ui_TargetTemp;
extern lv_obj_t * ui_TempSet;
extern lv_obj_t * ui_FAN;
extern lv_obj_t * ui_FANPic;
extern lv_obj_t * ui_FanPercent;
extern lv_obj_t * ui_Percent;
extern lv_obj_t * ui_FanUP;
extern lv_obj_t * ui_FanDown;
extern lv_obj_t * ui_USER1;
extern lv_obj_t * ui_USER2;
extern lv_obj_t * ui_USER3;
extern lv_obj_t * ui_USER4;
extern lv_obj_t * ui_StartStop;
extern lv_obj_t * ui_USER6;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_740489818);    // assets/material-symbols_thermostat-rounded.png
LV_IMG_DECLARE(ui_img_1699618864);    // assets/material-symbols_volume-up-outline-rounded.png
LV_IMG_DECLARE(ui_img_1956478733);    // assets/material-symbols_heat.png
LV_IMG_DECLARE(ui_img_155116563);    // assets/material-symbols_instant-mix-rounded.png
LV_IMG_DECLARE(ui_img_1162706898);    // assets/material-symbols_mode-fan-outline-sharp.png
LV_IMG_DECLARE(ui_img_1345483443);    // assets/material-symbols_fitbit-arrow-upward-rounded.png
LV_IMG_DECLARE(ui_img_817906860);    // assets/material-symbols_fitbit-arrow-downward-rounded.png
LV_IMG_DECLARE(ui_img_1577463476);    // assets/material-symbols_filter-1-outline-rounded.png
LV_IMG_DECLARE(ui_img_1006688281);    // assets/material-symbols_filter-2-outline-rounded.png
LV_IMG_DECLARE(ui_img_1428031618);    // assets/material-symbols_filter-3-outline-rounded.png
LV_IMG_DECLARE(ui_img_1680627741);    // assets/material-symbols_filter-4-outline-rounded.png
LV_IMG_DECLARE(ui_img_1347724781);    // assets/material-symbols_play-arrow-rounded.png
LV_IMG_DECLARE(ui_img_413634367);    // assets/material-symbols_stop-rounded.png
LV_IMG_DECLARE(ui_img_1671917170);    // assets/material-symbols_settings-rounded.png

// FONTS
LV_FONT_DECLARE(ui_font_ASCII);
LV_FONT_DECLARE(ui_font_ASCII48);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
