// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"

void ui_MainScreen_screen_init(void)
{
    ui_MainScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StatusDock = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_StatusDock);
    lv_obj_set_width(ui_StatusDock, 316);
    lv_obj_set_height(ui_StatusDock, 20);
    lv_obj_set_x(ui_StatusDock, 2);
    lv_obj_set_y(ui_StatusDock, 2);
    lv_obj_clear_flag(ui_StatusDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StatusDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StatusDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StatusDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Temp = lv_label_create(ui_StatusDock);
    lv_obj_set_width(ui_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Temp, 19);
    lv_obj_set_y(ui_Temp, 0);
    lv_obj_set_align(ui_Temp, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Temp, "00.00");
    lv_obj_set_style_text_color(ui_Temp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Temp, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempC = lv_label_create(ui_StatusDock);
    lv_obj_set_width(ui_TempC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempC, 60);
    lv_obj_set_y(ui_TempC, 0);
    lv_obj_set_align(ui_TempC, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TempC, "℃");
    lv_obj_set_style_text_color(ui_TempC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TempC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TempC, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempPic = lv_img_create(ui_StatusDock);
    lv_img_set_src(ui_TempPic, &ui_img_740489818);
    lv_obj_set_width(ui_TempPic, LV_SIZE_CONTENT);   /// 16
    lv_obj_set_height(ui_TempPic, LV_SIZE_CONTENT);    /// 16
    lv_obj_set_x(ui_TempPic, -5);
    lv_obj_set_y(ui_TempPic, 0);
    lv_obj_set_align(ui_TempPic, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_TempPic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_TempPic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_TempPic, 128);

    ui_BuzzerStatus = lv_img_create(ui_StatusDock);
    lv_img_set_src(ui_BuzzerStatus, &ui_img_1699618864);
    lv_obj_set_width(ui_BuzzerStatus, LV_SIZE_CONTENT);   /// 32
    lv_obj_set_height(ui_BuzzerStatus, LV_SIZE_CONTENT);    /// 32
    lv_obj_set_x(ui_BuzzerStatus, 5);
    lv_obj_set_y(ui_BuzzerStatus, 0);
    lv_obj_set_align(ui_BuzzerStatus, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_BuzzerStatus, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_BuzzerStatus, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_BuzzerStatus, 128);

    ui_HeatDock = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_HeatDock);
    lv_obj_set_width(ui_HeatDock, 210);
    lv_obj_set_height(ui_HeatDock, 72);
    lv_obj_set_x(ui_HeatDock, 2);
    lv_obj_set_y(ui_HeatDock, 28);
    lv_obj_clear_flag(ui_HeatDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HeatDock, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_HeatDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_HeatDock, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeatPic = lv_img_create(ui_HeatDock);
    lv_img_set_src(ui_HeatPic, &ui_img_1956478733);
    lv_obj_set_width(ui_HeatPic, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_HeatPic, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_HeatPic, 4);
    lv_obj_set_y(ui_HeatPic, 0);
    lv_obj_set_align(ui_HeatPic, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_HeatPic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_HeatPic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_HeatPic, 300);

    ui_HeatTemp = lv_label_create(ui_HeatDock);
    lv_obj_set_width(ui_HeatTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeatTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeatTemp, 66);
    lv_obj_set_y(ui_HeatTemp, -8);
    lv_obj_set_align(ui_HeatTemp, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_HeatTemp, "000");
    lv_obj_set_style_text_color(ui_HeatTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeatTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeatTemp, &ui_font_ASCII48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_HeatTempC = lv_label_create(ui_HeatDock);
    lv_obj_set_width(ui_HeatTempC, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeatTempC, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeatTempC, 140);
    lv_obj_set_y(ui_HeatTempC, -8);
    lv_obj_set_align(ui_HeatTempC, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_HeatTempC, "℃");
    lv_obj_set_style_text_color(ui_HeatTempC, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_HeatTempC, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_HeatTempC, &ui_font_ASCII48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Target = lv_label_create(ui_HeatDock);
    lv_obj_set_width(ui_Target, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Target, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Target, 68);
    lv_obj_set_y(ui_Target, 22);
    lv_obj_set_align(ui_Target, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Target, "TARGET:    ℃");
    lv_obj_set_style_text_color(ui_Target, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Target, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Target, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TargetTemp = lv_label_create(ui_HeatDock);
    lv_obj_set_width(ui_TargetTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TargetTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TargetTemp, 128);
    lv_obj_set_y(ui_TargetTemp, 22);
    lv_obj_set_align(ui_TargetTemp, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_TargetTemp, "000");
    lv_obj_set_style_text_color(ui_TargetTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TargetTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TargetTemp, &ui_font_ASCII, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempSet = lv_btn_create(ui_HeatDock);
    lv_obj_set_width(ui_TempSet, 32);
    lv_obj_set_height(ui_TempSet, 66);
    lv_obj_set_x(ui_TempSet, -3);
    lv_obj_set_y(ui_TempSet, 3);
    lv_obj_set_align(ui_TempSet, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_TempSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TempSet, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_TempSet, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_TempSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TempSet, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_TempSet, &ui_img_155116563, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_TempSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_TempSet, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FAN = lv_obj_create(ui_MainScreen);
    lv_obj_remove_style_all(ui_FAN);
    lv_obj_set_width(ui_FAN, 210);
    lv_obj_set_height(ui_FAN, 72);
    lv_obj_set_x(ui_FAN, 2);
    lv_obj_set_y(ui_FAN, 108);
    lv_obj_clear_flag(ui_FAN, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FAN, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FAN, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FAN, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FANPic = lv_img_create(ui_FAN);
    lv_img_set_src(ui_FANPic, &ui_img_1162706898);
    lv_obj_set_width(ui_FANPic, LV_SIZE_CONTENT);   /// 64
    lv_obj_set_height(ui_FANPic, LV_SIZE_CONTENT);    /// 64
    lv_obj_set_x(ui_FANPic, 4);
    lv_obj_set_y(ui_FANPic, 0);
    lv_obj_set_align(ui_FANPic, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_FANPic, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_FANPic, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_FANPic, 400);
    lv_img_set_zoom(ui_FANPic, 300);

    ui_FanPercent = lv_label_create(ui_FAN);
    lv_obj_set_width(ui_FanPercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_FanPercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_FanPercent, 66);
    lv_obj_set_y(ui_FanPercent, 0);
    lv_obj_set_align(ui_FanPercent, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_FanPercent, "000");
    lv_obj_set_style_text_color(ui_FanPercent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_FanPercent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_FanPercent, &ui_font_ASCII48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Percent = lv_label_create(ui_FAN);
    lv_obj_set_width(ui_Percent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Percent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Percent, 140);
    lv_obj_set_y(ui_Percent, 0);
    lv_obj_set_align(ui_Percent, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Percent, "%");
    lv_obj_set_style_text_color(ui_Percent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Percent, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Percent, &ui_font_ASCII48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanUP = lv_btn_create(ui_FAN);
    lv_obj_set_width(ui_FanUP, 32);
    lv_obj_set_height(ui_FanUP, 32);
    lv_obj_set_x(ui_FanUP, -3);
    lv_obj_set_y(ui_FanUP, 3);
    lv_obj_set_align(ui_FanUP, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_FanUP, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FanUP, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FanUP, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FanUP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FanUP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_FanUP, &ui_img_1345483443, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_FanUP, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_FanUP, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_FanDown = lv_btn_create(ui_FAN);
    lv_obj_set_width(ui_FanDown, 32);
    lv_obj_set_height(ui_FanDown, 32);
    lv_obj_set_x(ui_FanDown, -3);
    lv_obj_set_y(ui_FanDown, 37);
    lv_obj_set_align(ui_FanDown, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_FanDown, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_FanDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_FanDown, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_FanDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_FanDown, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_FanDown, &ui_img_817906860, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_FanDown, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_FanDown, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_USER1 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_USER1, 32);
    lv_obj_set_height(ui_USER1, 32);
    lv_obj_set_x(ui_USER1, -4);
    lv_obj_set_y(ui_USER1, 28);
    lv_obj_set_align(ui_USER1, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_USER1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_USER1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_USER1, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_USER1, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_USER1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_USER1, &ui_img_1577463476, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_USER1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_USER1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_USER1, &ui_img_1577463476, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor(ui_USER1, lv_color_hex(0x00FF8C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_USER1, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_USER2 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_USER2, 32);
    lv_obj_set_height(ui_USER2, 32);
    lv_obj_set_x(ui_USER2, -4);
    lv_obj_set_y(ui_USER2, 68);
    lv_obj_set_align(ui_USER2, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_USER2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_USER2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_USER2, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_USER2, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_USER2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_USER2, &ui_img_1006688281, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_USER2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_USER2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_USER2, &ui_img_1006688281, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor(ui_USER2, lv_color_hex(0x00FF8C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_USER2, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_USER3 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_USER3, 32);
    lv_obj_set_height(ui_USER3, 32);
    lv_obj_set_x(ui_USER3, -4);
    lv_obj_set_y(ui_USER3, 108);
    lv_obj_set_align(ui_USER3, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_USER3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_USER3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_USER3, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_USER3, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_USER3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_USER3, &ui_img_1428031618, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_USER3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_USER3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_USER3, &ui_img_1428031618, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor(ui_USER3, lv_color_hex(0x00FF8C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_USER3, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_USER4 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_USER4, 32);
    lv_obj_set_height(ui_USER4, 32);
    lv_obj_set_x(ui_USER4, -4);
    lv_obj_set_y(ui_USER4, 148);
    lv_obj_set_align(ui_USER4, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_USER4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_USER4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_USER4, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_USER4, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_USER4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_USER4, &ui_img_1680627741, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_tiled(ui_USER4, false, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_USER4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_USER4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_USER4, &ui_img_1680627741, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor(ui_USER4, lv_color_hex(0x00FF8C), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_img_recolor_opa(ui_USER4, 255, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_StartStop = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_StartStop, 56);
    lv_obj_set_height(ui_StartStop, 152);
    lv_obj_set_x(ui_StartStop, 220);
    lv_obj_set_y(ui_StartStop, 28);
    lv_obj_add_flag(ui_StartStop, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StartStop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_StartStop, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_StartStop, lv_color_hex(0x00FF8C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_StartStop, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_StartStop, &ui_img_1347724781, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_StartStop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_StartStop, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_StartStop, &ui_img_413634367, LV_PART_MAIN | LV_STATE_CHECKED);

    ui_USER6 = lv_btn_create(ui_MainScreen);
    lv_obj_set_width(ui_USER6, 64);
    lv_obj_set_height(ui_USER6, 44);
    lv_obj_set_x(ui_USER6, -254);
    lv_obj_set_y(ui_USER6, 188);
    lv_obj_set_align(ui_USER6, LV_ALIGN_TOP_RIGHT);
    lv_obj_add_flag(ui_USER6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_USER6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_USER6, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_USER6, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_USER6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_USER6, &ui_img_1671917170, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_USER6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_USER6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);


}
