// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#include "../ui.h"

void ui_ChartScreen_screen_init(void)
{
ui_ChartScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ChartScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ChartScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_ChartScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);

ui_ChartHeader = lv_obj_create(ui_ChartScreen);
lv_obj_remove_style_all(ui_ChartHeader);
lv_obj_set_width( ui_ChartHeader, 312);
lv_obj_set_height( ui_ChartHeader, 20);
lv_obj_set_x( ui_ChartHeader, 4 );
lv_obj_set_y( ui_ChartHeader, 2 );
lv_obj_clear_flag( ui_ChartHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ChartHeader, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ChartHeader, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ChartHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ChartRoomTemp = lv_label_create(ui_ChartHeader);
lv_obj_set_width( ui_ChartRoomTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ChartRoomTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ChartRoomTemp, 20 );
lv_obj_set_y( ui_ChartRoomTemp, 0 );
lv_obj_set_align( ui_ChartRoomTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_ChartRoomTemp,"00.00");
ui_object_set_themeable_style_property(ui_ChartRoomTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_ChartRoomTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_ChartRoomTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextChartRoomTemp = lv_label_create(ui_ChartHeader);
lv_obj_set_width( ui_TextChartRoomTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextChartRoomTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextChartRoomTemp, 60 );
lv_obj_set_y( ui_TextChartRoomTemp, 0 );
lv_obj_set_align( ui_TextChartRoomTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextChartRoomTemp,"℃");
ui_object_set_themeable_style_property(ui_TextChartRoomTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextChartRoomTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextChartRoomTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageChartRoomTemp = lv_img_create(ui_ChartHeader);
lv_img_set_src(ui_ImageChartRoomTemp, &ui_img_740489818);
lv_obj_set_width( ui_ImageChartRoomTemp, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_ImageChartRoomTemp, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_ImageChartRoomTemp, -5 );
lv_obj_set_y( ui_ImageChartRoomTemp, 0 );
lv_obj_set_align( ui_ImageChartRoomTemp, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageChartRoomTemp, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageChartRoomTemp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageChartRoomTemp,128);

ui_ChartBuzzerStatus = lv_img_create(ui_ChartHeader);
lv_img_set_src(ui_ChartBuzzerStatus, &ui_img_1699618864);
lv_obj_set_width( ui_ChartBuzzerStatus, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_ChartBuzzerStatus, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_ChartBuzzerStatus, 5 );
lv_obj_set_y( ui_ChartBuzzerStatus, 0 );
lv_obj_set_align( ui_ChartBuzzerStatus, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_ChartBuzzerStatus, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ChartBuzzerStatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ChartBuzzerStatus,128);

ui_ImageChartClock = lv_img_create(ui_ChartHeader);
lv_img_set_src(ui_ImageChartClock, &ui_img_290686881);
lv_obj_set_width( ui_ImageChartClock, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_ImageChartClock, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_ImageChartClock, 70 );
lv_obj_set_y( ui_ImageChartClock, 0 );
lv_obj_set_align( ui_ImageChartClock, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageChartClock, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageChartClock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageChartClock,128);

ui_ChartMinute = lv_label_create(ui_ChartHeader);
lv_obj_set_width( ui_ChartMinute, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ChartMinute, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ChartMinute, 95 );
lv_obj_set_y( ui_ChartMinute, 0 );
lv_obj_set_align( ui_ChartMinute, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_ChartMinute,"00");
ui_object_set_themeable_style_property(ui_ChartMinute, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_ChartMinute, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_ChartMinute, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ChartSecond = lv_label_create(ui_ChartHeader);
lv_obj_set_width( ui_ChartSecond, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ChartSecond, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ChartSecond, 119 );
lv_obj_set_y( ui_ChartSecond, 0 );
lv_obj_set_align( ui_ChartSecond, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_ChartSecond,"00");
ui_object_set_themeable_style_property(ui_ChartSecond, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_ChartSecond, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_ChartSecond, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextChartTime = lv_label_create(ui_ChartHeader);
lv_obj_set_width( ui_TextChartTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextChartTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextChartTime, 111 );
lv_obj_set_y( ui_TextChartTime, 0 );
lv_obj_set_align( ui_TextChartTime, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextChartTime,":");
ui_object_set_themeable_style_property(ui_TextChartTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextChartTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextChartTime, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ChartScreenBack = lv_btn_create(ui_ChartScreen);
lv_obj_set_width( ui_ChartScreenBack, 32);
lv_obj_set_height( ui_ChartScreenBack, 212);
lv_obj_set_x( ui_ChartScreenBack, -286 );
lv_obj_set_y( ui_ChartScreenBack, 25 );
lv_obj_set_align( ui_ChartScreenBack, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_ChartScreenBack, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ChartScreenBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ChartScreenBack, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ChartScreenBack, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ChartScreenBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_ChartScreenBack, &ui_img_852573520, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_ChartScreenBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ChartScreenBack, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ChartScreenDock = lv_obj_create(ui_ChartScreen);
lv_obj_remove_style_all(ui_ChartScreenDock);
lv_obj_set_width( ui_ChartScreenDock, 282);
lv_obj_set_height( ui_ChartScreenDock, 64);
lv_obj_set_x( ui_ChartScreenDock, 36 );
lv_obj_set_y( ui_ChartScreenDock, 25 );
lv_obj_clear_flag( ui_ChartScreenDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ChartScreenDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ChartScreenDock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_ChartScreenDock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);

ui_ChartTemp = lv_label_create(ui_ChartScreenDock);
lv_obj_set_width( ui_ChartTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ChartTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ChartTemp, 6 );
lv_obj_set_y( ui_ChartTemp, -8 );
lv_obj_set_align( ui_ChartTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_ChartTemp,"000");
ui_object_set_themeable_style_property(ui_ChartTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_ChartTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_ChartTemp, &ui_font_ASCII48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextChartTemp = lv_label_create(ui_ChartScreenDock);
lv_obj_set_width( ui_TextChartTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextChartTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextChartTemp, 80 );
lv_obj_set_y( ui_TextChartTemp, -8 );
lv_obj_set_align( ui_TextChartTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextChartTemp,"℃");
ui_object_set_themeable_style_property(ui_TextChartTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextChartTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextChartTemp, &ui_font_ASCII48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextChatTargetTemp = lv_label_create(ui_ChartScreenDock);
lv_obj_set_width( ui_TextChatTargetTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextChatTargetTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextChatTargetTemp, 8 );
lv_obj_set_y( ui_TextChatTargetTemp, 22 );
lv_obj_set_align( ui_TextChatTargetTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextChatTargetTemp,"TARGET:    ℃");
ui_object_set_themeable_style_property(ui_TextChatTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextChatTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextChatTargetTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ChartTargetTemp = lv_label_create(ui_ChartScreenDock);
lv_obj_set_width( ui_ChartTargetTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ChartTargetTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ChartTargetTemp, 68 );
lv_obj_set_y( ui_ChartTargetTemp, 22 );
lv_obj_set_align( ui_ChartTargetTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_ChartTargetTemp,"000");
ui_object_set_themeable_style_property(ui_ChartTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_ChartTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_ChartTargetTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ChartTempSet = lv_btn_create(ui_ChartScreenDock);
lv_obj_set_width( ui_ChartTempSet, 82);
lv_obj_set_height( ui_ChartTempSet, 60);
lv_obj_set_x( ui_ChartTempSet, 110 );
lv_obj_set_y( ui_ChartTempSet, 0 );
lv_obj_set_align( ui_ChartTempSet, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ChartTempSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ChartTempSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ChartTempSet, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ChartTempSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ChartTempSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_ChartTempSet, &ui_img_155116563, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_ChartTempSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ChartTempSet, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ChartSwitch = lv_btn_create(ui_ChartScreenDock);
lv_obj_set_width( ui_ChartSwitch, 82);
lv_obj_set_height( ui_ChartSwitch, 60);
lv_obj_set_x( ui_ChartSwitch, -2 );
lv_obj_set_y( ui_ChartSwitch, 2 );
lv_obj_set_align( ui_ChartSwitch, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_ChartSwitch, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ChartSwitch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ChartSwitch, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ChartSwitch, lv_color_hex(0x00FF8C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ChartSwitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_ChartSwitch, &ui_img_1347724781, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_ChartSwitch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ChartSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_ChartSwitch, &ui_img_413634367, LV_PART_MAIN | LV_STATE_CHECKED );

ui_ChartDock = lv_obj_create(ui_ChartScreen);
lv_obj_remove_style_all(ui_ChartDock);
lv_obj_set_width( ui_ChartDock, 282);
lv_obj_set_height( ui_ChartDock, 146);
lv_obj_set_x( ui_ChartDock, 36 );
lv_obj_set_y( ui_ChartDock, 91 );
lv_obj_clear_flag( ui_ChartDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ChartDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ChartDock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_Container);
ui_object_set_themeable_style_property(ui_ChartDock, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_Container);

ui_TempChart = lv_chart_create(ui_ChartDock);
lv_obj_set_width( ui_TempChart, 247);
lv_obj_set_height( ui_TempChart, 142);
lv_obj_set_x( ui_TempChart, 18 );
lv_obj_set_y( ui_TempChart, 2 );
lv_chart_set_type( ui_TempChart, LV_CHART_TYPE_LINE);
lv_chart_set_range( ui_TempChart, LV_CHART_AXIS_PRIMARY_Y, 0, 450);
lv_chart_set_div_line_count( ui_TempChart, 10, 0);
lv_chart_set_axis_tick( ui_TempChart, LV_CHART_AXIS_PRIMARY_X, 0, 0, 256, 0, false, 50);
lv_chart_set_axis_tick( ui_TempChart, LV_CHART_AXIS_PRIMARY_Y, 1, 0, 10, 1, true, 50);
lv_chart_set_axis_tick( ui_TempChart, LV_CHART_AXIS_SECONDARY_Y, 1, 0, 10, 1, true, 0);
ui_object_set_themeable_style_property(ui_TempChart, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TempChart, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_TextAndImage);


lv_obj_set_style_size(ui_TempChart, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_object_set_themeable_style_property(ui_TempChart, LV_PART_TICKS| LV_STATE_DEFAULT, LV_STYLE_LINE_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TempChart, LV_PART_TICKS| LV_STATE_DEFAULT, LV_STYLE_LINE_OPA, _ui_theme_alpha_TextAndImage);
ui_object_set_themeable_style_property(ui_TempChart, LV_PART_TICKS| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TempChart, LV_PART_TICKS| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TempChart, &ui_font_Chart, LV_PART_TICKS| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ChartScreenBack, ui_event_ChartScreenBack, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ChartTempSet, ui_event_ChartTempSet, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ChartSwitch, ui_event_ChartSwitch, LV_EVENT_ALL, NULL);

}
