// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StatusHeader = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_StatusHeader);
lv_obj_set_width( ui_StatusHeader, 312);
lv_obj_set_height( ui_StatusHeader, 20);
lv_obj_set_x( ui_StatusHeader, 4 );
lv_obj_set_y( ui_StatusHeader, 2 );
lv_obj_clear_flag( ui_StatusHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_StatusHeader, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_StatusHeader, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StatusHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomTemp = lv_label_create(ui_StatusHeader);
lv_obj_set_width( ui_RoomTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomTemp, 20 );
lv_obj_set_y( ui_RoomTemp, 0 );
lv_obj_set_align( ui_RoomTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_RoomTemp,"00.00");
ui_object_set_themeable_style_property(ui_RoomTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_RoomTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_RoomTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextRoomTemp = lv_label_create(ui_StatusHeader);
lv_obj_set_width( ui_TextRoomTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextRoomTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextRoomTemp, 60 );
lv_obj_set_y( ui_TextRoomTemp, 0 );
lv_obj_set_align( ui_TextRoomTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextRoomTemp,"℃");
ui_object_set_themeable_style_property(ui_TextRoomTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextRoomTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextRoomTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageRoomTemp = lv_img_create(ui_StatusHeader);
lv_img_set_src(ui_ImageRoomTemp, &ui_img_740489818);
lv_obj_set_width( ui_ImageRoomTemp, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_ImageRoomTemp, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_ImageRoomTemp, -5 );
lv_obj_set_y( ui_ImageRoomTemp, 0 );
lv_obj_set_align( ui_ImageRoomTemp, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageRoomTemp, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageRoomTemp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageRoomTemp,128);

ui_BuzzerStatus = lv_img_create(ui_StatusHeader);
lv_img_set_src(ui_BuzzerStatus, &ui_img_1699618864);
lv_obj_set_width( ui_BuzzerStatus, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_BuzzerStatus, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_BuzzerStatus, 5 );
lv_obj_set_y( ui_BuzzerStatus, 0 );
lv_obj_set_align( ui_BuzzerStatus, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_BuzzerStatus, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BuzzerStatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_BuzzerStatus,128);

ui_ImageClock = lv_img_create(ui_StatusHeader);
lv_img_set_src(ui_ImageClock, &ui_img_290686881);
lv_obj_set_width( ui_ImageClock, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_ImageClock, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_ImageClock, 70 );
lv_obj_set_y( ui_ImageClock, 0 );
lv_obj_set_align( ui_ImageClock, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageClock, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageClock, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageClock,128);

ui_Minute = lv_label_create(ui_StatusHeader);
lv_obj_set_width( ui_Minute, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Minute, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Minute, 95 );
lv_obj_set_y( ui_Minute, 0 );
lv_obj_set_align( ui_Minute, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Minute,"00");
ui_object_set_themeable_style_property(ui_Minute, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_Minute, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_Minute, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Second = lv_label_create(ui_StatusHeader);
lv_obj_set_width( ui_Second, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Second, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Second, 119 );
lv_obj_set_y( ui_Second, 0 );
lv_obj_set_align( ui_Second, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_Second,"00");
ui_object_set_themeable_style_property(ui_Second, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_Second, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_Second, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextTime = lv_label_create(ui_StatusHeader);
lv_obj_set_width( ui_TextTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextTime, 111 );
lv_obj_set_y( ui_TextTime, 0 );
lv_obj_set_align( ui_TextTime, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_TextTime,":");
ui_object_set_themeable_style_property(ui_TextTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextTime, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextTime, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeaterSetDock = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_HeaterSetDock);
lv_obj_set_width( ui_HeaterSetDock, 210);
lv_obj_set_height( ui_HeaterSetDock, 66);
lv_obj_set_x( ui_HeaterSetDock, 4 );
lv_obj_set_y( ui_HeaterSetDock, -60 );
lv_obj_set_align( ui_HeaterSetDock, LV_ALIGN_BOTTOM_LEFT );
lv_obj_clear_flag( ui_HeaterSetDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeaterSetDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeaterSetDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeaterSetDock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageHeater = lv_img_create(ui_HeaterSetDock);
lv_img_set_src(ui_ImageHeater, &ui_img_1956478733);
lv_obj_set_width( ui_ImageHeater, LV_SIZE_CONTENT);  /// 64
lv_obj_set_height( ui_ImageHeater, LV_SIZE_CONTENT);   /// 64
lv_obj_set_x( ui_ImageHeater, 0 );
lv_obj_set_y( ui_ImageHeater, -1 );
lv_obj_set_align( ui_ImageHeater, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_ImageHeater, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageHeater, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageHeater,300);

ui_TextTarget = lv_label_create(ui_HeaterSetDock);
lv_obj_set_width( ui_TextTarget, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextTarget, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextTarget, 58 );
lv_obj_set_y( ui_TextTarget, 3 );
lv_label_set_text(ui_TextTarget,"TARGET:");
ui_object_set_themeable_style_property(ui_TextTarget, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextTarget, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextTarget, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TargetTemp = lv_label_create(ui_HeaterSetDock);
lv_obj_set_width( ui_TargetTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TargetTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TargetTemp, 55 );
lv_obj_set_y( ui_TargetTemp, 21 );
lv_label_set_text(ui_TargetTemp,"000");
ui_object_set_themeable_style_property(ui_TargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TargetTemp, &ui_font_ASCII48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextTargetTemp = lv_label_create(ui_HeaterSetDock);
lv_obj_set_width( ui_TextTargetTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextTargetTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextTargetTemp, 128 );
lv_obj_set_y( ui_TextTargetTemp, 21 );
lv_label_set_text(ui_TextTargetTemp,"℃");
ui_object_set_themeable_style_property(ui_TextTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextTargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextTargetTemp, &ui_font_ASCII48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempSet = lv_btn_create(ui_HeaterSetDock);
lv_obj_set_width( ui_TempSet, 47);
lv_obj_set_height( ui_TempSet, 58);
lv_obj_set_x( ui_TempSet, -4 );
lv_obj_set_y( ui_TempSet, 4 );
lv_obj_set_align( ui_TempSet, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_TempSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_TempSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TempSet, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TempSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TempSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_TempSet, &ui_img_155116563, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_TempSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_TempSet, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeaterTempDock = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_HeaterTempDock);
lv_obj_set_width( ui_HeaterTempDock, 210);
lv_obj_set_height( ui_HeaterTempDock, 82);
lv_obj_set_x( ui_HeaterTempDock, 4 );
lv_obj_set_y( ui_HeaterTempDock, 28 );
lv_obj_clear_flag( ui_HeaterTempDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BarHeaterTemp = lv_bar_create(ui_HeaterTempDock);
lv_bar_set_range(ui_BarHeaterTemp, 0,400);
lv_obj_set_width( ui_BarHeaterTemp, 210);
lv_obj_set_height( ui_BarHeaterTemp, 82);
lv_obj_set_align( ui_BarHeaterTemp, LV_ALIGN_CENTER );
lv_obj_set_style_radius(ui_BarHeaterTemp, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BarHeaterTemp, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BarHeaterTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_BarHeaterTemp, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BarHeaterTemp, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BarHeaterTemp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_HeaterTemp = lv_label_create(ui_HeaterTempDock);
lv_obj_set_width( ui_HeaterTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HeaterTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeaterTemp, 6 );
lv_obj_set_y( ui_HeaterTemp, -6 );
lv_label_set_text(ui_HeaterTemp,"000");
ui_object_set_themeable_style_property(ui_HeaterTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_HeaterTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_HeaterTemp, &ui_font_ASCII96, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextHeaterTemp = lv_label_create(ui_HeaterTempDock);
lv_obj_set_width( ui_TextHeaterTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextHeaterTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextHeaterTemp, 158 );
lv_obj_set_y( ui_TextHeaterTemp, -6 );
lv_label_set_text(ui_TextHeaterTemp,"℃");
ui_object_set_themeable_style_property(ui_TextHeaterTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextHeaterTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextHeaterTemp, &ui_font_ASCII96, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Setting = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_Setting, 96);
lv_obj_set_height( ui_Setting, 44);
lv_obj_set_x( ui_Setting, -4 );
lv_obj_set_y( ui_Setting, 188 );
lv_obj_set_align( ui_Setting, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_Setting, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Setting, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Setting, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Setting, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Setting, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Setting, &ui_img_1671917170, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_Setting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Setting, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BuzzerSwitch = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_BuzzerSwitch, 66);
lv_obj_set_height( ui_BuzzerSwitch, 44);
lv_obj_set_x( ui_BuzzerSwitch, 76 );
lv_obj_set_y( ui_BuzzerSwitch, 188 );
lv_obj_add_flag( ui_BuzzerSwitch, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_BuzzerSwitch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_BuzzerSwitch, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_BuzzerSwitch, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_BuzzerSwitch, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonPressed);
lv_obj_set_style_bg_img_src( ui_BuzzerSwitch, &ui_img_185202102, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_BuzzerSwitch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BuzzerSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_BuzzerSwitch, 5, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_BuzzerSwitch, &ui_img_1699618864, LV_PART_MAIN | LV_STATE_CHECKED );

ui_FanSwitch = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_FanSwitch, 66);
lv_obj_set_height( ui_FanSwitch, 44);
lv_obj_set_x( ui_FanSwitch, 4 );
lv_obj_set_y( ui_FanSwitch, 188 );
lv_obj_add_flag( ui_FanSwitch, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_FanSwitch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_FanSwitch, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_FanSwitch, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_FanSwitch, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonPressed);
lv_obj_set_style_bg_img_src( ui_FanSwitch, &ui_img_2103744591, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_FanSwitch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_FanSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_FanSwitch, 5, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_FanSwitch, &ui_img_1708415670, LV_PART_MAIN | LV_STATE_CHECKED );

ui_ScreenSwitch = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_ScreenSwitch, 66);
lv_obj_set_height( ui_ScreenSwitch, 44);
lv_obj_set_x( ui_ScreenSwitch, 148 );
lv_obj_set_y( ui_ScreenSwitch, 188 );
lv_obj_add_flag( ui_ScreenSwitch, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ScreenSwitch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ScreenSwitch, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_ScreenSwitch, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonPressed);
ui_object_set_themeable_style_property(ui_ScreenSwitch, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonPressed);
lv_obj_set_style_bg_img_src( ui_ScreenSwitch, &ui_img_921610142, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_ScreenSwitch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_ScreenSwitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_ScreenSwitch, 5, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_img_src( ui_ScreenSwitch, &ui_img_1699618864, LV_PART_MAIN | LV_STATE_CHECKED );

ui_StartStop = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_StartStop, 96);
lv_obj_set_height( ui_StartStop, 152);
lv_obj_set_x( ui_StartStop, 220 );
lv_obj_set_y( ui_StartStop, 28 );
lv_obj_add_flag( ui_StartStop, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_StartStop, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_StartStop, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_StartStop, lv_color_hex(0x00FF8C), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StartStop, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_StartStop, &ui_img_1347724781, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_StartStop, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_StartStop, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_StartStop, &ui_img_413634367, LV_PART_MAIN | LV_STATE_CHECKED );

lv_obj_add_event_cb(ui_TempSet, ui_event_TempSet, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Setting, ui_event_Setting, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_BuzzerSwitch, ui_event_BuzzerSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_FanSwitch, ui_event_FanSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_ScreenSwitch, ui_event_ScreenSwitch, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_StartStop, ui_event_StartStop, LV_EVENT_ALL, NULL);

}
