// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t *ui_MainScreen;
lv_obj_t *ui_StatusHeader;
lv_obj_t *ui_RoomTemp;
lv_obj_t *ui_ImageRoomTemp;
lv_obj_t *ui_RoomTemp2;
lv_obj_t *ui_RoomTemp3;
lv_obj_t *ui_RoomTemp4;
lv_obj_t *ui_StatusHeader2;
lv_obj_t *ui_BuzzerStatus;
lv_obj_t *ui_Image1;
lv_obj_t *ui_Image2;
void ui_event_Setting( lv_event_t * e);
lv_obj_t *ui_Setting;
lv_obj_t *ui_Container2;
lv_obj_t *ui_Label1;
lv_obj_t *ui_Image3;
lv_obj_t *ui_Container1;
lv_obj_t *ui_HeaterTempDock;
lv_obj_t *ui_BarHeaterTemp;
lv_obj_t *ui_HeaterTemp;
lv_obj_t *ui_TextHeaterTemp;
lv_obj_t *ui_HeaterSetDock;
lv_obj_t *ui_TextTarget;
lv_obj_t *ui_TargetTemp;
void ui_event_TempSet( lv_event_t * e);
lv_obj_t *ui_TempSet;
lv_obj_t *ui_TempSet2;
lv_obj_t *ui_Container5;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Image5;
lv_obj_t *ui_Container3;
lv_obj_t *ui_HeaterTempDock2;
lv_obj_t *ui_BarHeaterTemp2;
lv_obj_t *ui_HeaterTemp2;
lv_obj_t *ui_TextHeaterTemp2;
lv_obj_t *ui_HeaterSetDock2;
lv_obj_t *ui_TextTarget2;
lv_obj_t *ui_TargetTemp2;
lv_obj_t *ui_TextTarget3;
lv_obj_t *ui_TargetTemp3;
void ui_event_TempSet4( lv_event_t * e);
lv_obj_t *ui_TempSet4;
lv_obj_t *ui_TempSet1;
// CUSTOM VARIABLES

// SCREEN: ui_TemperatureSettingScreen
void ui_TemperatureSettingScreen_screen_init(void);
lv_obj_t *ui_TemperatureSettingScreen;
lv_obj_t *ui_Keyboard;
void ui_event_Confirm( lv_event_t * e);
lv_obj_t *ui_Confirm;
void ui_event_Delete( lv_event_t * e);
lv_obj_t *ui_Delete;
void ui_event_Num0( lv_event_t * e);
lv_obj_t *ui_Num0;
lv_obj_t *ui_NumPanel;
void ui_event_Num1( lv_event_t * e);
lv_obj_t *ui_Num1;
void ui_event_Num2( lv_event_t * e);
lv_obj_t *ui_Num2;
void ui_event_Num3( lv_event_t * e);
lv_obj_t *ui_Num3;
void ui_event_Num4( lv_event_t * e);
lv_obj_t *ui_Num4;
void ui_event_Num5( lv_event_t * e);
lv_obj_t *ui_Num5;
void ui_event_Num6( lv_event_t * e);
lv_obj_t *ui_Num6;
void ui_event_Num7( lv_event_t * e);
lv_obj_t *ui_Num7;
void ui_event_Num8( lv_event_t * e);
lv_obj_t *ui_Num8;
void ui_event_Num9( lv_event_t * e);
lv_obj_t *ui_Num9;
lv_obj_t *ui_TempSettingHeader;
lv_obj_t *ui_TextTempSetting;
lv_obj_t *ui_TempSetting;
lv_obj_t *ui_SetTemp;
lv_obj_t *ui_TextSetTemp;
lv_obj_t *ui_TextCurrentTemp;
lv_obj_t *ui_CurrentTemp;
void ui_event_TempSettingBack( lv_event_t * e);
lv_obj_t *ui_TempSettingBack;
// CUSTOM VARIABLES

// SCREEN: ui_SystemSettingScreen
void ui_SystemSettingScreen_screen_init(void);
lv_obj_t *ui_SystemSettingScreen;
lv_obj_t *ui_SystemSettingHeader;
lv_obj_t *ui_ImageSystemHeader;
void ui_event_SystemSettingBack( lv_event_t * e);
lv_obj_t *ui_SystemSettingBack;
lv_obj_t *ui_SettingMenuDock;
lv_obj_t *ui_CustomCurve;
lv_obj_t *ui_ImageCurve;
lv_obj_t *ui_TextCurve;
void ui_event_PIDSetting( lv_event_t * e);
lv_obj_t *ui_PIDSetting;
lv_obj_t *ui_ImagePIDSetting;
lv_obj_t *ui_TextPIDSetting;
lv_obj_t *ui_TempLimited;
void ui_event_SliderTempLimited( lv_event_t * e);
lv_obj_t *ui_SliderTempLimited;
lv_obj_t *ui_ImageTempLimited;
lv_obj_t *ui_TextTempLimited;
lv_obj_t *ui_SleepTime;
void ui_event_SliderSleepTime( lv_event_t * e);
lv_obj_t *ui_SliderSleepTime;
lv_obj_t *ui_ImageSleepTime;
lv_obj_t *ui_TextSleepTime;
lv_obj_t *ui_Brightness;
void ui_event_SliderBrightness( lv_event_t * e);
lv_obj_t *ui_SliderBrightness;
lv_obj_t *ui_ImageBrightness;
lv_obj_t *ui_TextBrightness;
void ui_event_SaveConfig( lv_event_t * e);
lv_obj_t *ui_SaveConfig;
// CUSTOM VARIABLES

// SCREEN: ui_PIDSettingScreen
void ui_PIDSettingScreen_screen_init(void);
lv_obj_t *ui_PIDSettingScreen;
lv_obj_t *ui_PIDSettingHeader;
lv_obj_t *ui_TextPIDSettingHeader;
void ui_event_PIDSettingBack( lv_event_t * e);
lv_obj_t *ui_PIDSettingBack;
lv_obj_t *ui_PIDSettingDock;
void ui_event_KPSpinBox( lv_event_t * e);
lv_obj_t *ui_KPSpinBox;
lv_obj_t *ui_TextPIDKP;
void ui_event_KISpinBox( lv_event_t * e);
lv_obj_t *ui_KISpinBox;
lv_obj_t *ui_TextPIDKI;
void ui_event_KDSpinBox( lv_event_t * e);
lv_obj_t *ui_KDSpinBox;
lv_obj_t *ui_TextPIDKD;
void ui_event_KPDown( lv_event_t * e);
lv_obj_t *ui_KPDown;
void ui_event_KPUp( lv_event_t * e);
lv_obj_t *ui_KPUp;
void ui_event_KIDown( lv_event_t * e);
lv_obj_t *ui_KIDown;
void ui_event_KIUp( lv_event_t * e);
lv_obj_t *ui_KIUp;
void ui_event_KDDown( lv_event_t * e);
lv_obj_t *ui_KDDown;
void ui_event_KDUp( lv_event_t * e);
lv_obj_t *ui_KDUp;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Setting( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_SystemSettingScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_SystemSettingScreen_screen_init);
}
}

void ui_event_TempSet( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_TemperatureSettingScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_TemperatureSettingScreen_screen_init);
}
}

void ui_event_TempSet4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_TemperatureSettingScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_TemperatureSettingScreen_screen_init);
}
}

void ui_event_Confirm( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_MainScreen_screen_init);
}
}

void ui_event_Delete( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_label_set_property(ui_SetTemp, _UI_LABEL_PROPERTY_TEXT, "000");
}
}

void ui_event_Num0( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_label_set_property(ui_SetTemp, _UI_LABEL_PROPERTY_TEXT, "0");
}
}

void ui_event_Num1( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_label_set_property(ui_SetTemp, _UI_LABEL_PROPERTY_TEXT, "1");
}
}

void ui_event_Num2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_label_set_property(ui_SetTemp, _UI_LABEL_PROPERTY_TEXT, "2");
}
}

void ui_event_Num3( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_label_set_property(ui_SetTemp, _UI_LABEL_PROPERTY_TEXT, "3");
}
}

void ui_event_Num4( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_label_set_property(ui_SetTemp, _UI_LABEL_PROPERTY_TEXT, "4");
}
}

void ui_event_Num5( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_label_set_property(ui_SetTemp, _UI_LABEL_PROPERTY_TEXT, "5");
}
}

void ui_event_Num6( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_label_set_property(ui_SetTemp, _UI_LABEL_PROPERTY_TEXT, "6");
}
}

void ui_event_Num7( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_label_set_property(ui_SetTemp, _UI_LABEL_PROPERTY_TEXT, "7");
}
}

void ui_event_Num8( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_label_set_property(ui_SetTemp, _UI_LABEL_PROPERTY_TEXT, "8");
}
}

void ui_event_Num9( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_label_set_property(ui_SetTemp, _UI_LABEL_PROPERTY_TEXT, "9");
}
}

void ui_event_TempSettingBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_MainScreen_screen_init);
}
}

void ui_event_SystemSettingBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_MainScreen_screen_init);
}
}

void ui_event_PIDSetting( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_PIDSettingScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_PIDSettingScreen_screen_init);
}
}

void ui_event_SliderTempLimited( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_TextTempLimited, target, "", "℃");
}
}

void ui_event_SliderSleepTime( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_TextSleepTime, target, "", "Min");
}
}

void ui_event_SliderBrightness( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_TextBrightness, target, "", "%");
}
}

void ui_event_SaveConfig( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      SaveConfig( e );
}
}

void ui_event_PIDSettingBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_SystemSettingScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SystemSettingScreen_screen_init);
}
}

void ui_event_KPSpinBox( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      KpUpdate( e );
}
}

void ui_event_KISpinBox( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      KiUpdate( e );
}
}

void ui_event_KDSpinBox( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      KdUpdate( e );
}
}

void ui_event_KPDown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      PIDKPMinus( e );
}
}

void ui_event_KPUp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      PIDKPPlus( e );
}
}

void ui_event_KIDown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      PIDKIMinus( e );
}
}

void ui_event_KIUp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      PIDKIPlus( e );
}
}

void ui_event_KDDown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      PIDKDMinus( e );
}
}

void ui_event_KDUp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      PIDKDPlus( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_MainScreen_screen_init();
ui_TemperatureSettingScreen_screen_init();
ui_SystemSettingScreen_screen_init();
ui_PIDSettingScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_MainScreen);
}
