// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
lv_obj_t *ui_MainScreen;
void ui_event_Setting( lv_event_t * e);
lv_obj_t *ui_Setting;
lv_obj_t *ui_TMP102Dock;
lv_obj_t *ui_TMP102Temp;
lv_obj_t *ui_ImageTMP102Temp;
lv_obj_t *ui_INA226Voltage;
lv_obj_t *ui_INA226Current;
lv_obj_t *ui_INA226Power;
lv_obj_t *ui_SystemStatusDock;
lv_obj_t *ui_BuzzerStatus;
lv_obj_t *ui_SleepStatus;
lv_obj_t *ui_CoolingStatus;
lv_obj_t *ui_Soldering;
lv_obj_t *ui_TextSoldering;
lv_obj_t *ui_ImageSoldering;
lv_obj_t *ui_SolderingDock;
lv_obj_t *ui_SolderingTempDock;
lv_obj_t *ui_BarSolderingTemp;
lv_obj_t *ui_SolderingTemp;
lv_obj_t *ui_TextSolderingTemp;
lv_obj_t *ui_SolderingSettingDock;
lv_obj_t *ui_TextSolderingTragetTemp;
lv_obj_t *ui_SolderingTargetTemp;
void ui_event_SolderingSet( lv_event_t * e);
lv_obj_t *ui_SolderingSet;
void ui_event_SplderingSwitch( lv_event_t * e);
lv_obj_t *ui_SplderingSwitch;
lv_obj_t *ui_Heatgun;
lv_obj_t *ui_TextHeatgun;
lv_obj_t *ui_ImageHeatgun;
lv_obj_t *ui_HeatgunDock;
lv_obj_t *ui_HeatgunTempDock;
lv_obj_t *ui_BarHeatgunTemp;
lv_obj_t *ui_HeatgunTemp;
lv_obj_t *ui_TextHeatgunTemp;
lv_obj_t *ui_HeatgunSettingDock;
lv_obj_t *ui_TextHeatgunTargetTemp;
lv_obj_t *ui_HeatgunTargetTemp;
lv_obj_t *ui_TextHeatgunWindSpeed;
lv_obj_t *ui_HeatgunWindSpeed;
void ui_event_HeatgunSet( lv_event_t * e);
lv_obj_t *ui_HeatgunSet;
void ui_event_HeatgunSwitch( lv_event_t * e);
lv_obj_t *ui_HeatgunSwitch;
// CUSTOM VARIABLES

// SCREEN: ui_SolderingTempSetScreen
void ui_SolderingTempSetScreen_screen_init(void);
lv_obj_t *ui_SolderingTempSetScreen;
lv_obj_t *ui_SolderingKeyboard;
void ui_event_SolderingConfirm( lv_event_t * e);
lv_obj_t *ui_SolderingConfirm;
void ui_event_SolderingDelete( lv_event_t * e);
lv_obj_t *ui_SolderingDelete;
void ui_event_SolderingNum0( lv_event_t * e);
lv_obj_t *ui_SolderingNum0;
lv_obj_t *ui_SolderingNumPanel;
void ui_event_SolderingNum1( lv_event_t * e);
lv_obj_t *ui_SolderingNum1;
void ui_event_SolderingNum2( lv_event_t * e);
lv_obj_t *ui_SolderingNum2;
void ui_event_SolderingNum3( lv_event_t * e);
lv_obj_t *ui_SolderingNum3;
void ui_event_SolderingNum4( lv_event_t * e);
lv_obj_t *ui_SolderingNum4;
void ui_event_SolderingNum5( lv_event_t * e);
lv_obj_t *ui_SolderingNum5;
void ui_event_SolderingNum6( lv_event_t * e);
lv_obj_t *ui_SolderingNum6;
void ui_event_SolderingNum7( lv_event_t * e);
lv_obj_t *ui_SolderingNum7;
void ui_event_SolderingNum8( lv_event_t * e);
lv_obj_t *ui_SolderingNum8;
void ui_event_SolderingNum9( lv_event_t * e);
lv_obj_t *ui_SolderingNum9;
lv_obj_t *ui_SolderingTempSetDock;
lv_obj_t *ui_TextSolderingTempSetting;
lv_obj_t *ui_SolderingTempSetting;
lv_obj_t *ui_SolderingSetTemp;
lv_obj_t *ui_TextSolderingCurrentTemp;
lv_obj_t *ui_SolderingCurrentTemp;
void ui_event_SolderingTempSetBack( lv_event_t * e);
lv_obj_t *ui_SolderingTempSetBack;
// CUSTOM VARIABLES

// SCREEN: ui_HeatgunTempSetScreen
void ui_HeatgunTempSetScreen_screen_init(void);
lv_obj_t *ui_HeatgunTempSetScreen;
lv_obj_t *ui_HeatgunKeyboard;
void ui_event_HeatgunConfirm( lv_event_t * e);
lv_obj_t *ui_HeatgunConfirm;
void ui_event_HeatgunDelete( lv_event_t * e);
lv_obj_t *ui_HeatgunDelete;
void ui_event_HeatgunNum0( lv_event_t * e);
lv_obj_t *ui_HeatgunNum0;
lv_obj_t *ui_HeatgunNumPanel;
void ui_event_HeatgunNum1( lv_event_t * e);
lv_obj_t *ui_HeatgunNum1;
void ui_event_HeatgunNum2( lv_event_t * e);
lv_obj_t *ui_HeatgunNum2;
void ui_event_HeatgunNum3( lv_event_t * e);
lv_obj_t *ui_HeatgunNum3;
void ui_event_HeatgunNum4( lv_event_t * e);
lv_obj_t *ui_HeatgunNum4;
void ui_event_HeatgunNum5( lv_event_t * e);
lv_obj_t *ui_HeatgunNum5;
void ui_event_HeatgunNum6( lv_event_t * e);
lv_obj_t *ui_HeatgunNum6;
void ui_event_HeatgunNum7( lv_event_t * e);
lv_obj_t *ui_HeatgunNum7;
void ui_event_HeatgunNum8( lv_event_t * e);
lv_obj_t *ui_HeatgunNum8;
void ui_event_HeatgunNum9( lv_event_t * e);
lv_obj_t *ui_HeatgunNum9;
lv_obj_t *ui_HeatgunSetDock;
lv_obj_t *ui_TextHeatgunSetting;
lv_obj_t *ui_HeatgunSetting;
void ui_event_HeatgunSetTemp( lv_event_t * e);
lv_obj_t *ui_HeatgunSetTemp;
lv_obj_t *ui_TextHeatgunCurrentTemp;
lv_obj_t *ui_HeatgunCurrentTemp;
void ui_event_HeatgunSetWindSpeed( lv_event_t * e);
lv_obj_t *ui_HeatgunSetWindSpeed;
lv_obj_t *ui_TextHeatgunCurrentWindSpeed;
lv_obj_t *ui_HeatgunCurrentWindSpeed;
void ui_event_HeatgunSetBack( lv_event_t * e);
lv_obj_t *ui_HeatgunSetBack;
// CUSTOM VARIABLES

// SCREEN: ui_SystemSettingScreen
void ui_SystemSettingScreen_screen_init(void);
lv_obj_t *ui_SystemSettingScreen;
lv_obj_t *ui_SystemSettingHeader;
lv_obj_t *ui_ImageSystemHeader;
void ui_event_SystemSettingBack( lv_event_t * e);
lv_obj_t *ui_SystemSettingBack;
lv_obj_t *ui_SettingMenuDock;
lv_obj_t *ui_CustomCurve;
lv_obj_t *ui_ImageCurve;
lv_obj_t *ui_TextCurve;
void ui_event_PIDSetting( lv_event_t * e);
lv_obj_t *ui_PIDSetting;
lv_obj_t *ui_ImagePIDSetting;
lv_obj_t *ui_TextPIDSetting;
lv_obj_t *ui_TempLimited;
void ui_event_SliderTempLimited( lv_event_t * e);
lv_obj_t *ui_SliderTempLimited;
lv_obj_t *ui_ImageTempLimited;
lv_obj_t *ui_TextTempLimited;
lv_obj_t *ui_SleepTime;
void ui_event_SliderSleepTime( lv_event_t * e);
lv_obj_t *ui_SliderSleepTime;
lv_obj_t *ui_ImageSleepTime;
lv_obj_t *ui_TextSleepTime;
lv_obj_t *ui_Brightness;
void ui_event_SliderBrightness( lv_event_t * e);
lv_obj_t *ui_SliderBrightness;
lv_obj_t *ui_ImageBrightness;
lv_obj_t *ui_TextBrightness;
void ui_event_SaveConfig( lv_event_t * e);
lv_obj_t *ui_SaveConfig;
// CUSTOM VARIABLES

// SCREEN: ui_PIDSettingScreen
void ui_PIDSettingScreen_screen_init(void);
lv_obj_t *ui_PIDSettingScreen;
lv_obj_t *ui_PIDSettingHeader;
lv_obj_t *ui_TextPIDSettingHeader;
void ui_event_PIDSettingBack( lv_event_t * e);
lv_obj_t *ui_PIDSettingBack;
lv_obj_t *ui_PIDSettingDock;
void ui_event_KPSpinBox( lv_event_t * e);
lv_obj_t *ui_KPSpinBox;
lv_obj_t *ui_TextPIDKP;
void ui_event_KISpinBox( lv_event_t * e);
lv_obj_t *ui_KISpinBox;
lv_obj_t *ui_TextPIDKI;
void ui_event_KDSpinBox( lv_event_t * e);
lv_obj_t *ui_KDSpinBox;
lv_obj_t *ui_TextPIDKD;
void ui_event_KPDown( lv_event_t * e);
lv_obj_t *ui_KPDown;
void ui_event_KPUp( lv_event_t * e);
lv_obj_t *ui_KPUp;
void ui_event_KIDown( lv_event_t * e);
lv_obj_t *ui_KIDown;
void ui_event_KIUp( lv_event_t * e);
lv_obj_t *ui_KIUp;
void ui_event_KDDown( lv_event_t * e);
lv_obj_t *ui_KDDown;
void ui_event_KDUp( lv_event_t * e);
lv_obj_t *ui_KDUp;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

void ui_event_SystemSettingBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_MainScreen, LV_SCR_LOAD_ANIM_FADE_ON, 50, 0, &ui_MainScreen_screen_init);
}
}

void ui_event_PIDSetting( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      _ui_screen_change( &ui_PIDSettingScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_PIDSettingScreen_screen_init);
}
}

void ui_event_SliderTempLimited( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_TextTempLimited, target, "", "℃");
}
}

void ui_event_SliderSleepTime( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_TextSleepTime, target, "", "Min");
}
}

void ui_event_SliderBrightness( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_slider_set_text_value( ui_TextBrightness, target, "", "%");
}
}

void ui_event_SaveConfig( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      SaveConfig( e );
}
}

void ui_event_PIDSettingBack( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_RELEASED) {
      _ui_screen_change( &ui_SystemSettingScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_SystemSettingScreen_screen_init);
}
}

void ui_event_KPSpinBox( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      KpUpdate( e );
}
}

void ui_event_KISpinBox( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      KiUpdate( e );
}
}

void ui_event_KDSpinBox( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      KdUpdate( e );
}
}

void ui_event_KPDown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      PIDKPMinus( e );
}
}

void ui_event_KPUp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      PIDKPPlus( e );
}
}

void ui_event_KIDown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      PIDKIMinus( e );
}
}

void ui_event_KIUp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      PIDKIPlus( e );
}
}

void ui_event_KDDown( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      PIDKDMinus( e );
}
}

void ui_event_KDUp( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_PRESSED) {
      PIDKDPlus( e );
}
}

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_MainScreen_screen_init();
ui_SolderingTempSetScreen_screen_init();
ui_HeatgunTempSetScreen_screen_init();
ui_SystemSettingScreen_screen_init();
ui_PIDSettingScreen_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_MainScreen);
}
