// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI

#ifndef _UI_UI_H
#define _UI_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_MainScreen
void ui_MainScreen_screen_init(void);
extern lv_obj_t *ui_MainScreen;
extern lv_obj_t *ui_StatusHeader;
extern lv_obj_t *ui_RoomTemp;
extern lv_obj_t *ui_ImageRoomTemp;
extern lv_obj_t *ui_RoomTemp2;
extern lv_obj_t *ui_RoomTemp3;
extern lv_obj_t *ui_RoomTemp4;
extern lv_obj_t *ui_StatusHeader2;
extern lv_obj_t *ui_BuzzerStatus;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Image2;
void ui_event_Setting( lv_event_t * e);
extern lv_obj_t *ui_Setting;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_HeaterTempDock;
extern lv_obj_t *ui_BarHeaterTemp;
extern lv_obj_t *ui_HeaterTemp;
extern lv_obj_t *ui_TextHeaterTemp;
extern lv_obj_t *ui_HeaterSetDock;
extern lv_obj_t *ui_TextTarget;
extern lv_obj_t *ui_TargetTemp;
void ui_event_TempSet( lv_event_t * e);
extern lv_obj_t *ui_TempSet;
extern lv_obj_t *ui_TempSet2;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_HeaterTempDock2;
extern lv_obj_t *ui_BarHeaterTemp2;
extern lv_obj_t *ui_HeaterTemp2;
extern lv_obj_t *ui_TextHeaterTemp2;
extern lv_obj_t *ui_HeaterSetDock2;
extern lv_obj_t *ui_TextTarget2;
extern lv_obj_t *ui_TargetTemp2;
extern lv_obj_t *ui_TextTarget3;
extern lv_obj_t *ui_TargetTemp3;
void ui_event_TempSet4( lv_event_t * e);
extern lv_obj_t *ui_TempSet4;
extern lv_obj_t *ui_TempSet1;
// CUSTOM VARIABLES

// SCREEN: ui_TemperatureSettingScreen
void ui_TemperatureSettingScreen_screen_init(void);
extern lv_obj_t *ui_TemperatureSettingScreen;
extern lv_obj_t *ui_Keyboard;
void ui_event_Confirm( lv_event_t * e);
extern lv_obj_t *ui_Confirm;
void ui_event_Delete( lv_event_t * e);
extern lv_obj_t *ui_Delete;
void ui_event_Num0( lv_event_t * e);
extern lv_obj_t *ui_Num0;
extern lv_obj_t *ui_NumPanel;
void ui_event_Num1( lv_event_t * e);
extern lv_obj_t *ui_Num1;
void ui_event_Num2( lv_event_t * e);
extern lv_obj_t *ui_Num2;
void ui_event_Num3( lv_event_t * e);
extern lv_obj_t *ui_Num3;
void ui_event_Num4( lv_event_t * e);
extern lv_obj_t *ui_Num4;
void ui_event_Num5( lv_event_t * e);
extern lv_obj_t *ui_Num5;
void ui_event_Num6( lv_event_t * e);
extern lv_obj_t *ui_Num6;
void ui_event_Num7( lv_event_t * e);
extern lv_obj_t *ui_Num7;
void ui_event_Num8( lv_event_t * e);
extern lv_obj_t *ui_Num8;
void ui_event_Num9( lv_event_t * e);
extern lv_obj_t *ui_Num9;
extern lv_obj_t *ui_TempSettingHeader;
extern lv_obj_t *ui_TextTempSetting;
extern lv_obj_t *ui_TempSetting;
extern lv_obj_t *ui_SetTemp;
extern lv_obj_t *ui_TextSetTemp;
extern lv_obj_t *ui_TextCurrentTemp;
extern lv_obj_t *ui_CurrentTemp;
void ui_event_TempSettingBack( lv_event_t * e);
extern lv_obj_t *ui_TempSettingBack;
// CUSTOM VARIABLES

// SCREEN: ui_SystemSettingScreen
void ui_SystemSettingScreen_screen_init(void);
extern lv_obj_t *ui_SystemSettingScreen;
extern lv_obj_t *ui_SystemSettingHeader;
extern lv_obj_t *ui_ImageSystemHeader;
void ui_event_SystemSettingBack( lv_event_t * e);
extern lv_obj_t *ui_SystemSettingBack;
extern lv_obj_t *ui_SettingMenuDock;
extern lv_obj_t *ui_CustomCurve;
extern lv_obj_t *ui_ImageCurve;
extern lv_obj_t *ui_TextCurve;
void ui_event_PIDSetting( lv_event_t * e);
extern lv_obj_t *ui_PIDSetting;
extern lv_obj_t *ui_ImagePIDSetting;
extern lv_obj_t *ui_TextPIDSetting;
extern lv_obj_t *ui_TempLimited;
void ui_event_SliderTempLimited( lv_event_t * e);
extern lv_obj_t *ui_SliderTempLimited;
extern lv_obj_t *ui_ImageTempLimited;
extern lv_obj_t *ui_TextTempLimited;
extern lv_obj_t *ui_SleepTime;
void ui_event_SliderSleepTime( lv_event_t * e);
extern lv_obj_t *ui_SliderSleepTime;
extern lv_obj_t *ui_ImageSleepTime;
extern lv_obj_t *ui_TextSleepTime;
extern lv_obj_t *ui_Brightness;
void ui_event_SliderBrightness( lv_event_t * e);
extern lv_obj_t *ui_SliderBrightness;
extern lv_obj_t *ui_ImageBrightness;
extern lv_obj_t *ui_TextBrightness;
void ui_event_SaveConfig( lv_event_t * e);
extern lv_obj_t *ui_SaveConfig;
// CUSTOM VARIABLES

// SCREEN: ui_PIDSettingScreen
void ui_PIDSettingScreen_screen_init(void);
extern lv_obj_t *ui_PIDSettingScreen;
extern lv_obj_t *ui_PIDSettingHeader;
extern lv_obj_t *ui_TextPIDSettingHeader;
void ui_event_PIDSettingBack( lv_event_t * e);
extern lv_obj_t *ui_PIDSettingBack;
extern lv_obj_t *ui_PIDSettingDock;
void ui_event_KPSpinBox( lv_event_t * e);
extern lv_obj_t *ui_KPSpinBox;
extern lv_obj_t *ui_TextPIDKP;
void ui_event_KISpinBox( lv_event_t * e);
extern lv_obj_t *ui_KISpinBox;
extern lv_obj_t *ui_TextPIDKI;
void ui_event_KDSpinBox( lv_event_t * e);
extern lv_obj_t *ui_KDSpinBox;
extern lv_obj_t *ui_TextPIDKD;
void ui_event_KPDown( lv_event_t * e);
extern lv_obj_t *ui_KPDown;
void ui_event_KPUp( lv_event_t * e);
extern lv_obj_t *ui_KPUp;
void ui_event_KIDown( lv_event_t * e);
extern lv_obj_t *ui_KIDown;
void ui_event_KIUp( lv_event_t * e);
extern lv_obj_t *ui_KIUp;
void ui_event_KDDown( lv_event_t * e);
extern lv_obj_t *ui_KDDown;
void ui_event_KDUp( lv_event_t * e);
extern lv_obj_t *ui_KDUp;
// CUSTOM VARIABLES

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_740489818);   // assets/material-symbols_thermostat-rounded.png
LV_IMG_DECLARE( ui_img_1699618864);   // assets/material-symbols_volume-up-outline-rounded.png
LV_IMG_DECLARE( ui_img_1249241237);   // assets/icon-park-solid_sleep.png
LV_IMG_DECLARE( ui_img_2103744591);   // assets/material-symbols_mode-fan-outline.png
LV_IMG_DECLARE( ui_img_1671917170);   // assets/material-symbols_settings-rounded.png
LV_IMG_DECLARE( ui_img_1357884022);   // assets/material-symbols_looks-one-rounded.png
LV_IMG_DECLARE( ui_img_155116563);   // assets/material-symbols_instant-mix-rounded.png
LV_IMG_DECLARE( ui_img_1347724781);   // assets/material-symbols_play-arrow-rounded.png
LV_IMG_DECLARE( ui_img_413634367);   // assets/material-symbols_stop-rounded.png
LV_IMG_DECLARE( ui_img_2126869900);   // assets/material-symbols_looks-two-rounded.png
LV_IMG_DECLARE( ui_img_938671949);   // assets/material-symbols_check-rounded.png
LV_IMG_DECLARE( ui_img_13634893);   // assets/material-symbols_close-rounded.png
LV_IMG_DECLARE( ui_img_num0_png);   // assets/Num0.png
LV_IMG_DECLARE( ui_img_num1_png);   // assets/Num1.png
LV_IMG_DECLARE( ui_img_num2_png);   // assets/Num2.png
LV_IMG_DECLARE( ui_img_num3_png);   // assets/Num3.png
LV_IMG_DECLARE( ui_img_num4_png);   // assets/Num4.png
LV_IMG_DECLARE( ui_img_num5_png);   // assets/Num5.png
LV_IMG_DECLARE( ui_img_num6_png);   // assets/Num6.png
LV_IMG_DECLARE( ui_img_num7_png);   // assets/Num7.png
LV_IMG_DECLARE( ui_img_num8_png);   // assets/Num8.png
LV_IMG_DECLARE( ui_img_num9_png);   // assets/Num9.png
LV_IMG_DECLARE( ui_img_852573520);   // assets/material-symbols_chevron-left-rounded.png
LV_IMG_DECLARE( ui_img_1205510230);   // assets/material-symbols_storage-rounded.png
LV_IMG_DECLARE( ui_img_329106951);   // assets/material-symbols_speed-outline-rounded.png
LV_IMG_DECLARE( ui_img_295618317);   // assets/material-symbols_avg-pace-rounded.png
LV_IMG_DECLARE( ui_img_637286161);   // assets/material-symbols_backlight-high-rounded.png
LV_IMG_DECLARE( ui_img_1723942165);   // assets/material-symbols_save-outline-rounded.png
LV_IMG_DECLARE( ui_img_minus_png);   // assets/minus.png
LV_IMG_DECLARE( ui_img_plus_png);   // assets/plus.png
LV_IMG_DECLARE( ui_img_817906860);   // assets/material-symbols_fitbit-arrow-downward-rounded.png
LV_IMG_DECLARE( ui_img_1345483443);   // assets/material-symbols_fitbit-arrow-upward-rounded.png
LV_IMG_DECLARE( ui_img_1956478733);   // assets/material-symbols_heat.png
LV_IMG_DECLARE( ui_img_1708415670);   // assets/material-symbols_mode-fan-off-outline-sharp.png
LV_IMG_DECLARE( ui_img_1162706898);   // assets/material-symbols_mode-fan-outline-sharp.png
LV_IMG_DECLARE( ui_img_921610142);   // assets/material-symbols_screen-share-outline-rounded.png
LV_IMG_DECLARE( ui_img_290686881);   // assets/material-symbols_search-activity-rounded.png
LV_IMG_DECLARE( ui_img_185202102);   // assets/material-symbols_volume-off-outline-rounded.png

// FONTS
LV_FONT_DECLARE( ui_font_ASCII);
LV_FONT_DECLARE( ui_font_ASCII24);
LV_FONT_DECLARE( ui_font_ASCII32);
LV_FONT_DECLARE( ui_font_ASCII48);
LV_FONT_DECLARE( ui_font_ASCII88);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
