// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"

void HeatingStart(lv_event_t * e)
{
	// Your code here
}

void HeatingStop(lv_event_t * e)
{
	// Your code here
}

void PIDCalibrationStart(lv_event_t * e)
{
	// Your code here
}

void PIDCalibrationStop(lv_event_t * e)
{
	// Your code here
}

void SaveConfig(lv_event_t * e)
{
	// Your code here
}

void KpUpdate(lv_event_t * e)
{
	// Your code here
}

void KiUpdate(lv_event_t * e)
{
	// Your code here
}

void KdUpdate(lv_event_t * e)
{
	// Your code here
}

void PIDKPMinus(lv_event_t * e)
{
	// Your code here
}

void PIDKPPlus(lv_event_t * e)
{
	// Your code here
}

void PIDKIMinus(lv_event_t * e)
{
	// Your code here
}

void PIDKIPlus(lv_event_t * e)
{
	// Your code here
}

void PIDKDMinus(lv_event_t * e)
{
	// Your code here
}

void PIDKDPlus(lv_event_t * e)
{
	// Your code here
}
