// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: UI

#include "ui.h"

void HeatingStart(lv_event_t * e)
{
	// Your code here
}

void HeatingStop(lv_event_t * e)
{
	// Your code here
}

void PIDCalibrationStart(lv_event_t * e)
{
	// Your code here
}

void PIDCalibrationStop(lv_event_t * e)
{
	// Your code here
}

void SaveConfig(lv_event_t * e)
{
	// Your code here
}

void KpUpdate(lv_event_t * e)
{
	// Your code here
}

void KiUpdate(lv_event_t * e)
{
	// Your code here
}

void KdUpdate(lv_event_t * e)
{
	// Your code here
}

void PIDKPMinus(lv_event_t * e)
{
	// Your code here
}

void PIDKPPlus(lv_event_t * e)
{
	// Your code here
}

void PIDKIMinus(lv_event_t * e)
{
	// Your code here
}

void PIDKIPlus(lv_event_t * e)
{
	// Your code here
}

void PIDKDMinus(lv_event_t * e)
{
	// Your code here
}

void PIDKDPlus(lv_event_t * e)
{
	// Your code here
}

void SolderingON(lv_event_t * e)
{
	// Your code here
}

void SolderingOFF(lv_event_t * e)
{
	// Your code here
}

void HeatgunON(lv_event_t * e)
{
	// Your code here
}

void HeatgunOFF(lv_event_t * e)
{
	// Your code here
}

void HeatgunDelete(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum0(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum1(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum2(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum3(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum4(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum5(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum6(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum7(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum8(lv_event_t * e)
{
	// Your code here
}

void HeatgunNum9(lv_event_t * e)
{
	// Your code here
}
