// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: UI

#include "../ui.h"

void ui_MainScreen_screen_init(void)
{
ui_MainScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_MainScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_MainScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_COLOR, _ui_theme_color_ButtonAndBack);
ui_object_set_themeable_style_property(ui_MainScreen, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BG_OPA, _ui_theme_alpha_ButtonAndBack);

ui_StatusHeader = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_StatusHeader);
lv_obj_set_width( ui_StatusHeader, 74);
lv_obj_set_height( ui_StatusHeader, 20);
lv_obj_set_x( ui_StatusHeader, 2 );
lv_obj_set_y( ui_StatusHeader, 2 );
lv_obj_clear_flag( ui_StatusHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_StatusHeader, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_StatusHeader, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StatusHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_StatusHeader, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_StatusHeader, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_StatusHeader, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomTemp = lv_label_create(ui_StatusHeader);
lv_obj_set_width( ui_RoomTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomTemp, 20 );
lv_obj_set_y( ui_RoomTemp, 0 );
lv_obj_set_align( ui_RoomTemp, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_RoomTemp,"00.00℃");
ui_object_set_themeable_style_property(ui_RoomTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_RoomTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_RoomTemp, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageRoomTemp = lv_img_create(ui_StatusHeader);
lv_img_set_src(ui_ImageRoomTemp, &ui_img_740489818);
lv_obj_set_width( ui_ImageRoomTemp, LV_SIZE_CONTENT);  /// 16
lv_obj_set_height( ui_ImageRoomTemp, LV_SIZE_CONTENT);   /// 16
lv_obj_set_x( ui_ImageRoomTemp, -5 );
lv_obj_set_y( ui_ImageRoomTemp, 0 );
lv_obj_set_align( ui_ImageRoomTemp, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_ImageRoomTemp, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageRoomTemp, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_ImageRoomTemp,128);

ui_RoomTemp2 = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_RoomTemp2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomTemp2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomTemp2, 78 );
lv_obj_set_y( ui_RoomTemp2, -108 );
lv_obj_set_align( ui_RoomTemp2, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_RoomTemp2,"00.00V");
lv_obj_set_style_text_color(ui_RoomTemp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RoomTemp2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RoomTemp2, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_RoomTemp2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomTemp2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomTemp2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomTemp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomTemp2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomTemp2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_RoomTemp2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_RoomTemp2, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_RoomTemp2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_RoomTemp2, -1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomTemp3 = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_RoomTemp3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomTemp3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomTemp3, 136 );
lv_obj_set_y( ui_RoomTemp3, -108 );
lv_obj_set_align( ui_RoomTemp3, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_RoomTemp3,"00.00A");
lv_obj_set_style_text_color(ui_RoomTemp3, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RoomTemp3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RoomTemp3, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_RoomTemp3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomTemp3, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomTemp3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomTemp3, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomTemp3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomTemp3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_RoomTemp3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_RoomTemp3, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_RoomTemp3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_RoomTemp3, -1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RoomTemp4 = lv_label_create(ui_MainScreen);
lv_obj_set_width( ui_RoomTemp4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_RoomTemp4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_RoomTemp4, 194 );
lv_obj_set_y( ui_RoomTemp4, -108 );
lv_obj_set_align( ui_RoomTemp4, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_RoomTemp4,"00.00W");
lv_obj_set_style_text_color(ui_RoomTemp4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_RoomTemp4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_RoomTemp4, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_RoomTemp4, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_RoomTemp4, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_RoomTemp4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_RoomTemp4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_RoomTemp4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_RoomTemp4, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_RoomTemp4, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_RoomTemp4, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_RoomTemp4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_RoomTemp4, -1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_StatusHeader2 = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_StatusHeader2);
lv_obj_set_width( ui_StatusHeader2, 66);
lv_obj_set_height( ui_StatusHeader2, 20);
lv_obj_set_x( ui_StatusHeader2, 252 );
lv_obj_set_y( ui_StatusHeader2, 2 );
lv_obj_clear_flag( ui_StatusHeader2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_StatusHeader2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_StatusHeader2, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_StatusHeader2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_StatusHeader2, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_StatusHeader2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_StatusHeader2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BuzzerStatus = lv_img_create(ui_StatusHeader2);
lv_img_set_src(ui_BuzzerStatus, &ui_img_1699618864);
lv_obj_set_width( ui_BuzzerStatus, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_BuzzerStatus, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_BuzzerStatus, -6 );
lv_obj_set_y( ui_BuzzerStatus, 0 );
lv_obj_set_align( ui_BuzzerStatus, LV_ALIGN_LEFT_MID );
lv_obj_add_flag( ui_BuzzerStatus, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_BuzzerStatus, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_BuzzerStatus,128);

ui_Image1 = lv_img_create(ui_StatusHeader2);
lv_img_set_src(ui_Image1, &ui_img_1249241237);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 32
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image1,128);

ui_Image2 = lv_img_create(ui_StatusHeader2);
lv_img_set_src(ui_Image2, &ui_img_2103744591);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_Image2, 6 );
lv_obj_set_y( ui_Image2, 0 );
lv_obj_set_align( ui_Image2, LV_ALIGN_RIGHT_MID );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image2,128);

ui_Setting = lv_btn_create(ui_MainScreen);
lv_obj_set_width( ui_Setting, 96);
lv_obj_set_height( ui_Setting, 44);
lv_obj_set_x( ui_Setting, -2 );
lv_obj_set_y( ui_Setting, 193 );
lv_obj_set_align( ui_Setting, LV_ALIGN_TOP_RIGHT );
lv_obj_add_flag( ui_Setting, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Setting, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Setting, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Setting, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Setting, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_Setting, &ui_img_1671917170, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_color(ui_Setting, lv_color_hex(0x6E6E6E), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Setting, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Setting, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_Setting, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_Setting, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container2 = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, 156);
lv_obj_set_height( ui_Container2, 166);
lv_obj_set_x( ui_Container2, 2 );
lv_obj_set_y( ui_Container2, 24 );
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Container2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Container2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Container2);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label1, 20 );
lv_obj_set_y( ui_Label1, -2 );
lv_label_set_text(ui_Label1,"SOLDERING");
lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label1, &ui_font_ASCII24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_Container2);
lv_img_set_src(ui_Image3, &ui_img_1357884022);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_Image3, -6 );
lv_obj_set_y( ui_Image3, -6 );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image3,190);
lv_obj_set_style_radius(ui_Image3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_Container2);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, 156);
lv_obj_set_height( ui_Container1, 142);
lv_obj_set_x( ui_Container1, -1 );
lv_obj_set_y( ui_Container1, 20 );
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Container1, lv_color_hex(0x31526B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Container1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container1, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeaterTempDock = lv_obj_create(ui_Container1);
lv_obj_remove_style_all(ui_HeaterTempDock);
lv_obj_set_width( ui_HeaterTempDock, 152);
lv_obj_set_height( ui_HeaterTempDock, 69);
lv_obj_set_x( ui_HeaterTempDock, 1 );
lv_obj_set_y( ui_HeaterTempDock, 1 );
lv_obj_clear_flag( ui_HeaterTempDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BarHeaterTemp = lv_bar_create(ui_HeaterTempDock);
lv_bar_set_value(ui_BarHeaterTemp,10,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BarHeaterTemp, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BarHeaterTemp, 152);
lv_obj_set_height( ui_BarHeaterTemp, 69);
lv_obj_set_align( ui_BarHeaterTemp, LV_ALIGN_LEFT_MID );
lv_obj_set_style_radius(ui_BarHeaterTemp, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BarHeaterTemp, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BarHeaterTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_anim_time(ui_BarHeaterTemp, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_BarHeaterTemp, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BarHeaterTemp, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BarHeaterTemp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BarHeaterTemp, lv_color_hex(0x343131), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BarHeaterTemp, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_BarHeaterTemp, 20, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_BarHeaterTemp, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_BarHeaterTemp, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_BarHeaterTemp, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_HeaterTemp = lv_label_create(ui_HeaterTempDock);
lv_obj_set_width( ui_HeaterTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HeaterTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeaterTemp, -2 );
lv_obj_set_y( ui_HeaterTemp, -8 );
lv_label_set_text(ui_HeaterTemp,"000");
ui_object_set_themeable_style_property(ui_HeaterTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_HeaterTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_HeaterTemp, &ui_font_ASCII88, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_HeaterTemp, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeaterTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextHeaterTemp = lv_label_create(ui_HeaterTempDock);
lv_obj_set_width( ui_TextHeaterTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextHeaterTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextHeaterTemp, 126 );
lv_obj_set_y( ui_TextHeaterTemp, -1 );
lv_label_set_text(ui_TextHeaterTemp,"℃");
ui_object_set_themeable_style_property(ui_TextHeaterTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextHeaterTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextHeaterTemp, &ui_font_ASCII48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeaterSetDock = lv_obj_create(ui_Container1);
lv_obj_remove_style_all(ui_HeaterSetDock);
lv_obj_set_width( ui_HeaterSetDock, 152);
lv_obj_set_height( ui_HeaterSetDock, 67);
lv_obj_set_x( ui_HeaterSetDock, 0 );
lv_obj_set_y( ui_HeaterSetDock, 72 );
lv_obj_set_align( ui_HeaterSetDock, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_HeaterSetDock, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeaterSetDock, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeaterSetDock, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeaterSetDock, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextTarget = lv_label_create(ui_HeaterSetDock);
lv_obj_set_width( ui_TextTarget, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextTarget, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextTarget, 2 );
lv_obj_set_y( ui_TextTarget, 1 );
lv_label_set_text(ui_TextTarget,"设定温度:");
ui_object_set_themeable_style_property(ui_TextTarget, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextTarget, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextTarget, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TargetTemp = lv_label_create(ui_HeaterSetDock);
lv_obj_set_width( ui_TargetTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TargetTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TargetTemp, -10 );
lv_obj_set_y( ui_TargetTemp, 1 );
lv_obj_set_align( ui_TargetTemp, LV_ALIGN_TOP_RIGHT );
lv_label_set_text(ui_TargetTemp,"000℃");
lv_obj_add_flag( ui_TargetTemp, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE );   /// Flags
ui_object_set_themeable_style_property(ui_TargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TargetTemp, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TargetTemp, &ui_font_ASCII32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TargetTemp, -1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TargetTemp, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TargetTemp, -3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TargetTemp, -6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_TargetTemp, 5, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_TargetTemp, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_TargetTemp, 255, LV_PART_MAIN| LV_STATE_CHECKED);

ui_TempSet = lv_btn_create(ui_HeaterSetDock);
lv_obj_set_width( ui_TempSet, 72);
lv_obj_set_height( ui_TempSet, 36);
lv_obj_set_x( ui_TempSet, -2 );
lv_obj_set_y( ui_TempSet, -2 );
lv_obj_set_align( ui_TempSet, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_TempSet, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_TempSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TempSet, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TempSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TempSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_TempSet, &ui_img_155116563, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_TempSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_TempSet, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempSet2 = lv_btn_create(ui_HeaterSetDock);
lv_obj_set_width( ui_TempSet2, 72);
lv_obj_set_height( ui_TempSet2, 36);
lv_obj_set_x( ui_TempSet2, 2 );
lv_obj_set_y( ui_TempSet2, -2 );
lv_obj_set_align( ui_TempSet2, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_TempSet2, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_TempSet2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TempSet2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TempSet2, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TempSet2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_TempSet2, &ui_img_1347724781, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_TempSet2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_TempSet2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_TempSet2, &ui_img_413634367, LV_PART_MAIN | LV_STATE_CHECKED );

ui_Container5 = lv_obj_create(ui_MainScreen);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, 156);
lv_obj_set_height( ui_Container5, 166);
lv_obj_set_x( ui_Container5, 162 );
lv_obj_set_y( ui_Container5, 24 );
lv_obj_clear_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container5, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Container5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Container5, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container5, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label3 = lv_label_create(ui_Container5);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label3, 20 );
lv_obj_set_y( ui_Label3, -2 );
lv_label_set_text(ui_Label3,"HEATGUN");
lv_obj_set_style_text_color(ui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Label3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label3, &ui_font_ASCII24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image5 = lv_img_create(ui_Container5);
lv_img_set_src(ui_Image5, &ui_img_2126869900);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 32
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 32
lv_obj_set_x( ui_Image5, -6 );
lv_obj_set_y( ui_Image5, -6 );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_img_set_zoom(ui_Image5,190);

ui_Container3 = lv_obj_create(ui_Container5);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_width( ui_Container3, 156);
lv_obj_set_height( ui_Container3, 142);
lv_obj_set_x( ui_Container3, -1 );
lv_obj_set_y( ui_Container3, 20 );
lv_obj_clear_flag( ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container3, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Container3, lv_color_hex(0x31526B), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Container3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Container3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Container3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeaterTempDock2 = lv_obj_create(ui_Container3);
lv_obj_remove_style_all(ui_HeaterTempDock2);
lv_obj_set_width( ui_HeaterTempDock2, 152);
lv_obj_set_height( ui_HeaterTempDock2, 69);
lv_obj_set_x( ui_HeaterTempDock2, 1 );
lv_obj_set_y( ui_HeaterTempDock2, 1 );
lv_obj_clear_flag( ui_HeaterTempDock2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_BarHeaterTemp2 = lv_bar_create(ui_HeaterTempDock2);
lv_bar_set_value(ui_BarHeaterTemp2,10,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BarHeaterTemp2, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BarHeaterTemp2, 152);
lv_obj_set_height( ui_BarHeaterTemp2, 69);
lv_obj_set_align( ui_BarHeaterTemp2, LV_ALIGN_LEFT_MID );
lv_obj_set_style_radius(ui_BarHeaterTemp2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BarHeaterTemp2, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BarHeaterTemp2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_anim_time(ui_BarHeaterTemp2, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_radius(ui_BarHeaterTemp2, 5, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BarHeaterTemp2, lv_color_hex(0xFF0000), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BarHeaterTemp2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_BarHeaterTemp2, lv_color_hex(0x343131), LV_PART_INDICATOR | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_BarHeaterTemp2, 255, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_width(ui_BarHeaterTemp2, 20, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_spread(ui_BarHeaterTemp2, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_x(ui_BarHeaterTemp2, 4, LV_PART_INDICATOR| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_ofs_y(ui_BarHeaterTemp2, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

ui_HeaterTemp2 = lv_label_create(ui_HeaterTempDock2);
lv_obj_set_width( ui_HeaterTemp2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HeaterTemp2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HeaterTemp2, -2 );
lv_obj_set_y( ui_HeaterTemp2, -8 );
lv_label_set_text(ui_HeaterTemp2,"000");
lv_obj_set_style_text_color(ui_HeaterTemp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HeaterTemp2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HeaterTemp2, &ui_font_ASCII88, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_shadow_color(ui_HeaterTemp2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_HeaterTemp2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextHeaterTemp2 = lv_label_create(ui_HeaterTempDock2);
lv_obj_set_width( ui_TextHeaterTemp2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextHeaterTemp2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextHeaterTemp2, 126 );
lv_obj_set_y( ui_TextHeaterTemp2, -1 );
lv_label_set_text(ui_TextHeaterTemp2,"℃");
lv_obj_set_style_text_color(ui_TextHeaterTemp2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TextHeaterTemp2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TextHeaterTemp2, &ui_font_ASCII48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HeaterSetDock2 = lv_obj_create(ui_Container3);
lv_obj_remove_style_all(ui_HeaterSetDock2);
lv_obj_set_width( ui_HeaterSetDock2, 152);
lv_obj_set_height( ui_HeaterSetDock2, 67);
lv_obj_set_x( ui_HeaterSetDock2, 0 );
lv_obj_set_y( ui_HeaterSetDock2, 72 );
lv_obj_set_align( ui_HeaterSetDock2, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_HeaterSetDock2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_HeaterSetDock2, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_HeaterSetDock2, lv_color_hex(0x393939), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_HeaterSetDock2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TextTarget2 = lv_label_create(ui_HeaterSetDock2);
lv_obj_set_width( ui_TextTarget2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextTarget2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextTarget2, 2 );
lv_obj_set_y( ui_TextTarget2, -44 );
lv_obj_set_align( ui_TextTarget2, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_TextTarget2,"温度:");
ui_object_set_themeable_style_property(ui_TextTarget2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextTarget2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextTarget2, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TargetTemp2 = lv_label_create(ui_HeaterSetDock2);
lv_obj_set_width( ui_TargetTemp2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TargetTemp2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TargetTemp2, 41 );
lv_obj_set_y( ui_TargetTemp2, -45 );
lv_obj_set_align( ui_TargetTemp2, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_TargetTemp2,"000℃");
lv_obj_add_flag( ui_TargetTemp2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE );   /// Flags
ui_object_set_themeable_style_property(ui_TargetTemp2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TargetTemp2, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TargetTemp2, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TargetTemp2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TargetTemp2, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TargetTemp2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TargetTemp2, -2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_TargetTemp2, 3, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_TargetTemp2, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_TargetTemp2, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_left(ui_TargetTemp2, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_right(ui_TargetTemp2, 1, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_top(ui_TargetTemp2, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_bottom(ui_TargetTemp2, -2, LV_PART_MAIN| LV_STATE_CHECKED);

ui_TextTarget3 = lv_label_create(ui_HeaterSetDock2);
lv_obj_set_width( ui_TextTarget3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TextTarget3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TextTarget3, -34 );
lv_obj_set_y( ui_TextTarget3, -43 );
lv_obj_set_align( ui_TextTarget3, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_TextTarget3,"风速:");
ui_object_set_themeable_style_property(ui_TextTarget3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TextTarget3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TextTarget3, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TargetTemp3 = lv_label_create(ui_HeaterSetDock2);
lv_obj_set_width( ui_TargetTemp3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TargetTemp3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TargetTemp3, -2 );
lv_obj_set_y( ui_TargetTemp3, -45 );
lv_obj_set_align( ui_TargetTemp3, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_TargetTemp3,"000%");
lv_obj_add_flag( ui_TargetTemp3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_CHECKABLE );   /// Flags
ui_object_set_themeable_style_property(ui_TargetTemp3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_TextAndImage);
ui_object_set_themeable_style_property(ui_TargetTemp3, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_TextAndImage);
lv_obj_set_style_text_font(ui_TargetTemp3, &ui_font_ASCII, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TargetTemp3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TargetTemp3, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TargetTemp3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TargetTemp3, -2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_radius(ui_TargetTemp3, 3, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_bg_color(ui_TargetTemp3, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_TargetTemp3, 255, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_left(ui_TargetTemp3, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_right(ui_TargetTemp3, 1, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_top(ui_TargetTemp3, 0, LV_PART_MAIN| LV_STATE_CHECKED);
lv_obj_set_style_pad_bottom(ui_TargetTemp3, -2, LV_PART_MAIN| LV_STATE_CHECKED);

ui_TempSet4 = lv_btn_create(ui_HeaterSetDock2);
lv_obj_set_width( ui_TempSet4, 72);
lv_obj_set_height( ui_TempSet4, 36);
lv_obj_set_x( ui_TempSet4, 2 );
lv_obj_set_y( ui_TempSet4, -2 );
lv_obj_set_align( ui_TempSet4, LV_ALIGN_BOTTOM_LEFT );
lv_obj_add_flag( ui_TempSet4, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_TempSet4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TempSet4, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TempSet4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TempSet4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_TempSet4, &ui_img_155116563, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_TempSet4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_TempSet4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempSet1 = lv_btn_create(ui_HeaterSetDock2);
lv_obj_set_width( ui_TempSet1, 72);
lv_obj_set_height( ui_TempSet1, 36);
lv_obj_set_x( ui_TempSet1, -2 );
lv_obj_set_y( ui_TempSet1, -2 );
lv_obj_set_align( ui_TempSet1, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_add_flag( ui_TempSet1, LV_OBJ_FLAG_CHECKABLE | LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_TempSet1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TempSet1, 5, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TempSet1, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TempSet1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_TempSet1, &ui_img_1347724781, LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_color(ui_TempSet1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_shadow_opa(ui_TempSet1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_img_src( ui_TempSet1, &ui_img_413634367, LV_PART_MAIN | LV_STATE_CHECKED );

lv_obj_add_event_cb(ui_Setting, ui_event_Setting, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TempSet, ui_event_TempSet, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_TempSet4, ui_event_TempSet4, LV_EVENT_ALL, NULL);

}
